// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test} from "forge-std/Test.sol";
import {CurveMath} from "src/libraries/CurveMath.sol";
import {Curve1Zones} from "src/curves/Curve1Zones.sol";
import {Curve2Zones} from "src/curves/Curve2Zones.sol";
import {Curve3Zones} from "src/curves/Curve3Zones.sol";

/// @title RollingCurves — permanent behavioral suite for curve1/2/3 (rolling hills).
/// @notice GENERATED by ~/clawd/psp-rolling.py. DO NOT HAND-EDIT.
///         Anchors are exact CurveMath outputs; envelope P=1e-3*(R/2000)^1.660964
///         with (2000,1e-3) (8000,1e-2) (32000,1e-1) (128000,1) hit exactly.
contract RollingCurvesTest is Test {
    // ══ curve1 ════════════════════════════════════════════════════
    function test_Curve1Anchors() public pure {
        CurveMath.CurveConfig memory cc = Curve1Zones.config();
        // (S, P, R) captured from CurveMath — exact equality, envelope contract.
        assertEq(CurveMath.marginalPrice(5301814704124618325622784, cc), 999999999998960);
        assertEq(CurveMath.curveIntegral(0, 5301814704124618325622784, cc), 2000000000000888584922);
        assertEq(CurveMath.marginalPrice(6833153559965283081256960, cc), 9999999999991221);
        assertEq(CurveMath.curveIntegral(0, 6833153559965283081256960, cc), 7999999999995565255394);
        assertEq(CurveMath.marginalPrice(7441620828958361808535552, cc), 99999999999908255);
        assertEq(CurveMath.curveIntegral(0, 7441620828958361808535552, cc), 31999999999973380735598);
        assertEq(CurveMath.marginalPrice(7684488120277192656551936, cc), 999999999999060927);
        assertEq(CurveMath.curveIntegral(0, 7684488120277192656551936, cc), 127999999999883184502717);
    }

    function test_Curve1Monotone() public pure {
        CurveMath.CurveConfig memory cc = Curve1Zones.config();
        uint256 prevP = 0;
        uint256 prevR = 0;
        for (uint256 i = 1; i <= 512; i++) {
            uint256 s = 7684488120277192656551936 * i / 512;
            uint256 p = CurveMath.marginalPrice(s, cc);
            uint256 r = CurveMath.curveIntegral(0, s, cc);
            assertGe(p, prevP);   // price never decreases
            assertGt(r, prevR);   // reserve strictly accumulates
            prevP = p;
            prevR = r;
        }
    }

    function test_Curve1ZoneLiftsAndShape() public pure {
        CurveMath.CurveConfig memory cc = Curve1Zones.config();
        uint256 nz = cc.zones.length;
        assertEq(cc.zones[0].startSupply, 0);            // starts at origin
        assertTrue(cc.zones[0].isExponential);           // seed shelf (flat exp)
        assertTrue(!cc.zones[nz - 1].isExponential);     // log tail
        assertEq(cc.zones[nz - 1].endSupply, type(uint256).max); // unbounded
        for (uint256 i = 0; i < nz - 1; i++) {
            assertLt(cc.zones[i].startSupply, cc.zones[i].endSupply);
            uint256 pIn = CurveMath.marginalPrice(cc.zones[i].startSupply, cc);
            uint256 pOut = CurveMath.marginalPrice(cc.zones[i].endSupply, cc);
            assertGe(pOut, pIn);                         // every zone lifts
        }
        // S_end within [0.6x, 1.5x] of curvePrototype (similar amplitude)
        uint256 sEnd = cc.zones[nz - 2].endSupply;
        assertGe(sEnd, 4663465081448658125193216);
        assertLe(sEnd, 11658662703621645044547584);
    }

    function test_Curve1Telescoping() public pure {
        // B4j guarantee: any partition of a span sums bit-exactly.
        CurveMath.CurveConfig memory cc = Curve1Zones.config();
        uint256 a = 2561496040092397552183978; // S_end/3, precomputed
        uint256 b = 7040992362724194498117632;
        assertLe(a, b);
        uint256 r0a = CurveMath.curveIntegral(0, a, cc);
        uint256 rab = CurveMath.curveIntegral(a, b, cc);
        uint256 rbEnd = CurveMath.curveIntegral(b, 7684488120277192656551936, cc);
        assertEq(r0a + rab + rbEnd, CurveMath.curveIntegral(0, 7684488120277192656551936, cc));
    }
    // ══ curve2 ════════════════════════════════════════════════════
    function test_Curve2Anchors() public pure {
        CurveMath.CurveConfig memory cc = Curve2Zones.config();
        // (S, P, R) captured from CurveMath — exact equality, envelope contract.
        assertEq(CurveMath.marginalPrice(5187725977033414113492992, cc), 999999999999923);
        assertEq(CurveMath.curveIntegral(0, 5187725977033414113492992, cc), 2000000000001779862678);
        assertEq(CurveMath.marginalPrice(6407826056344963813212160, cc), 10000000000000773);
        assertEq(CurveMath.curveIntegral(0, 6407826056344963813212160, cc), 8000000000002119101550);
        assertEq(CurveMath.marginalPrice(6892971666068378828668928, cc), 100000000000012181);
        assertEq(CurveMath.curveIntegral(0, 6892971666068378828668928, cc), 32000000000004682623497);
        assertEq(CurveMath.marginalPrice(7086641525536812976570368, cc), 1000000000000094506);
        assertEq(CurveMath.curveIntegral(0, 7086641525536812976570368, cc), 128000000000014464505901);
    }

    function test_Curve2Monotone() public pure {
        CurveMath.CurveConfig memory cc = Curve2Zones.config();
        uint256 prevP = 0;
        uint256 prevR = 0;
        for (uint256 i = 1; i <= 512; i++) {
            uint256 s = 7086641525536812976570368 * i / 512;
            uint256 p = CurveMath.marginalPrice(s, cc);
            uint256 r = CurveMath.curveIntegral(0, s, cc);
            assertGe(p, prevP);   // price never decreases
            assertGt(r, prevR);   // reserve strictly accumulates
            prevP = p;
            prevR = r;
        }
    }

    function test_Curve2ZoneLiftsAndShape() public pure {
        CurveMath.CurveConfig memory cc = Curve2Zones.config();
        uint256 nz = cc.zones.length;
        assertEq(cc.zones[0].startSupply, 0);            // starts at origin
        assertTrue(cc.zones[0].isExponential);           // seed shelf (flat exp)
        assertTrue(!cc.zones[nz - 1].isExponential);     // log tail
        assertEq(cc.zones[nz - 1].endSupply, type(uint256).max); // unbounded
        for (uint256 i = 0; i < nz - 1; i++) {
            assertLt(cc.zones[i].startSupply, cc.zones[i].endSupply);
            uint256 pIn = CurveMath.marginalPrice(cc.zones[i].startSupply, cc);
            uint256 pOut = CurveMath.marginalPrice(cc.zones[i].endSupply, cc);
            assertGe(pOut, pIn);                         // every zone lifts
        }
        // S_end within [0.6x, 1.5x] of curvePrototype (similar amplitude)
        uint256 sEnd = cc.zones[nz - 2].endSupply;
        assertGe(sEnd, 4663465081448658125193216);
        assertLe(sEnd, 11658662703621645044547584);
    }

    function test_Curve2Telescoping() public pure {
        // B4j guarantee: any partition of a span sums bit-exactly.
        CurveMath.CurveConfig memory cc = Curve2Zones.config();
        uint256 a = 2362213841845604325523456; // S_end/3, precomputed
        uint256 b = 6514769537551930224541696;
        assertLe(a, b);
        uint256 r0a = CurveMath.curveIntegral(0, a, cc);
        uint256 rab = CurveMath.curveIntegral(a, b, cc);
        uint256 rbEnd = CurveMath.curveIntegral(b, 7086641525536812976570368, cc);
        assertEq(r0a + rab + rbEnd, CurveMath.curveIntegral(0, 7086641525536812976570368, cc));
    }
    // ══ curve3 ════════════════════════════════════════════════════
    function test_Curve3Anchors() public pure {
        CurveMath.CurveConfig memory cc = Curve3Zones.config();
        // (S, P, R) captured from CurveMath — exact equality, envelope contract.
        assertEq(CurveMath.marginalPrice(5137201534083818766467072, cc), 1000000000000488);
        assertEq(CurveMath.curveIntegral(0, 5137201534083818766467072, cc), 2000000000002465457595);
        assertEq(CurveMath.marginalPrice(6866229511586008493195264, cc), 10000000000005835);
        assertEq(CurveMath.curveIntegral(0, 6866229511586008493195264, cc), 8000000000006133539041);
        assertEq(CurveMath.marginalPrice(7557840702586884169138176, cc), 100000000000054352);
        assertEq(CurveMath.curveIntegral(0, 7557840702586884169138176, cc), 32000000000018956609154);
        assertEq(CurveMath.marginalPrice(7834485178987233151025152, cc), 1000000000000551846);
        assertEq(CurveMath.curveIntegral(0, 7834485178987233151025152, cc), 128000000000071354446561);
    }

    function test_Curve3Monotone() public pure {
        CurveMath.CurveConfig memory cc = Curve3Zones.config();
        uint256 prevP = 0;
        uint256 prevR = 0;
        for (uint256 i = 1; i <= 512; i++) {
            uint256 s = 7834485178987234224766976 * i / 512;
            uint256 p = CurveMath.marginalPrice(s, cc);
            uint256 r = CurveMath.curveIntegral(0, s, cc);
            assertGe(p, prevP);   // price never decreases
            assertGt(r, prevR);   // reserve strictly accumulates
            prevP = p;
            prevR = r;
        }
    }

    function test_Curve3ZoneLiftsAndShape() public pure {
        CurveMath.CurveConfig memory cc = Curve3Zones.config();
        uint256 nz = cc.zones.length;
        assertEq(cc.zones[0].startSupply, 0);            // starts at origin
        assertTrue(cc.zones[0].isExponential);           // seed shelf (flat exp)
        assertTrue(!cc.zones[nz - 1].isExponential);     // log tail
        assertEq(cc.zones[nz - 1].endSupply, type(uint256).max); // unbounded
        for (uint256 i = 0; i < nz - 1; i++) {
            assertLt(cc.zones[i].startSupply, cc.zones[i].endSupply);
            uint256 pIn = CurveMath.marginalPrice(cc.zones[i].startSupply, cc);
            uint256 pOut = CurveMath.marginalPrice(cc.zones[i].endSupply, cc);
            assertGe(pOut, pIn);                         // every zone lifts
        }
        // S_end within [0.6x, 1.5x] of curvePrototype (similar amplitude)
        uint256 sEnd = cc.zones[nz - 2].endSupply;
        assertGe(sEnd, 4663465081448658125193216);
        assertLe(sEnd, 11658662703621645044547584);
    }

    function test_Curve3Telescoping() public pure {
        // B4j guarantee: any partition of a span sums bit-exactly.
        CurveMath.CurveConfig memory cc = Curve3Zones.config();
        uint256 a = 2611495059662411408255658; // S_end/3, precomputed
        uint256 b = 6866229511586007419453440;
        assertLe(a, b);
        uint256 r0a = CurveMath.curveIntegral(0, a, cc);
        uint256 rab = CurveMath.curveIntegral(a, b, cc);
        uint256 rbEnd = CurveMath.curveIntegral(b, 7834485178987234224766976, cc);
        assertEq(r0a + rab + rbEnd, CurveMath.curveIntegral(0, 7834485178987234224766976, cc));
    }
}
