// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test, console2} from "forge-std/Test.sol";
import {SineMath} from "../src/libraries/SineMath.sol";
import {SineVectors as V} from "./SineVectors.sol";

/// @title SineMathTest — oracle-certified unit battery for the tilted-sine curve.
/// @notice Vectors are GENERATED by scripts/sine_oracle.py (float mirror of the
///         exact WAD algorithm, certified vs Simpson-20k at 7.1e-14 worst rel).
///         Structural tests (partition invariance, round-trip strictness,
///         monotonicity, boot-invariance) are self-contained.

/// @dev external frame so expectRevert can observe inlined library reverts
contract SineCaller {
    function callValidate(SineMath.Params memory p) external pure {
        SineMath.validate(p);
    }
}

contract SineMathTest is Test {
    using SineMath for SineMath.Params;

    SineMath.Curve curve;

    function setUp() public {
        SineMath.Params memory p = SineMath.Params({
            p0: V.P0, preK: V.PREK, magM: V.MAGM, lnTop: V.LNTOP, ampBps: 10_000
        });
        curve = SineMath.materialize(p, V.BOOT);
    }

    function _rel(uint256 a, uint256 b) internal pure returns (uint256) {
        // |a−b|/max(a,b) in WAD-scaled bps of 1e18 — returns rel error × 1e18
        uint256 d = a > b ? a - b : b - a;
        uint256 m = a > b ? a : b;
        if (m == 0) return 0;
        return d * 1e18 / m;
    }

    // ── sin precision ──
    function test_SinWad_MatchesFloat() public view {
        uint256[] memory xs = V.SIN_X();
        int256[] memory ys = V.SIN_Y();
        for (uint256 i = 0; i < xs.length; i++) {
            int256 got = SineMath._sinWad(xs[i]);
            int256 exp = ys[i];
            int256 d = got > exp ? got - exp : exp - got;
            assertLe(d, 2000, "sinWad drifted >2e-15 rel");
        }
    }

    // ── materialization ──
    function test_Materialize_AnchorsExact() public view {
        assertLe(_rel(curve.B, V.EXP_B), 1e15, "B anchor (integer rounding only)");
        assertLe(_rel(curve.pTop, V.EXP_PTOP), 1e15, "pTop anchor (integer rounding only)");
        assertLe(_rel(curve.q0, V.EXP_Q0), 1e9, "q0 (1e-9)");
        assertLe(_rel(curve.qTop, V.EXP_QTOP), 1e9, "qTop (1e-9)");
    }

    function test_Materialize_Checkpoints() public view {
        uint256[13] memory cp = V.EXP_CP();
        for (uint256 j = 0; j < 13; j++) {
            assertLe(_rel(curve.cp[j], cp[j]), 1e9, "checkpoint drift");
        }
    }

    // ── price / supply grids vs oracle ──
    function test_PriceGrid_Oracle() public view {
        uint256[] memory gr = V.GRID_R();
        uint256[] memory gp = V.GRID_P();
        for (uint256 i = 0; i < gr.length; i++) {
            assertLe(_rel(SineMath.priceAt(curve, gr[i]), gp[i]), 1e10, "price grid (1e-8)");
        }
    }

    function test_SupplyGrid_Oracle() public view {
        uint256[] memory gr = V.GRID_R();
        uint256[] memory gq = V.GRID_Q();
        for (uint256 i = 0; i < gr.length; i++) {
            assertLe(_rel(SineMath.supplyAt(curve, gr[i]), gq[i]), 1e9, "supply grid (1e-9)");
        }
    }

    function test_BuyVectors_Oracle() public view {
        uint256[] memory br = V.BUY_R();
        uint256[] memory bs = V.BUY_SPEND();
        uint256[] memory bo = V.BUY_OUT();
        for (uint256 i = 0; i < br.length; i++) {
            uint256 out = SineMath.buyOut(curve, br[i], bs[i]);
            assertLe(_rel(out, bo[i]), 1e9, "buy vector (1e-9)");
        }
    }

    function test_SellVectors_Oracle() public view {
        uint256[] memory sr = V.SELL_R();
        uint256[] memory si = V.SELL_IN();
        uint256[] memory so = V.SELL_OUT();
        for (uint256 i = 0; i < sr.length; i++) {
            uint256 out = SineMath.sellOut(curve, sr[i], si[i]);
            assertLe(_rel(out, so[i]), 1e7, "sell vector (1e-11)");
        }
    }

    // ── partition invariance (B4j class): EXACT telescoping, no tolerance ──
    function test_PartitionInvariance_Exact() public pure {
        SineMath.Params memory p = SineMath.Params({
            p0: V.P0, preK: V.PREK, magM: V.MAGM, lnTop: V.LNTOP, ampBps: 10_000
        });
        SineMath.Curve memory c = SineMath.materialize(p, V.BOOT);

        // bulk: buy 1234.5 mixETH at the launch seam
        uint256 spend = 1234.5e18;
        uint256 R0 = c.boot;
        uint256 bulk = SineMath.supplyAt(c, R0 + spend) - SineMath.supplyAt(c, R0);

        // chopped: 7 uneven pieces — integrals must telescope EXACTLY
        uint256[7] memory parts = [
            uint256(1.1e18), 200e18, 0.007e18, 999.993e18, 13e18, 20.398e18, 0.002e18
        ];
        uint256 R = R0;
        uint256 sum;
        for (uint256 i = 0; i < 7; i++) {
            sum += SineMath.supplyAt(c, R + parts[i]) - SineMath.supplyAt(c, R);
            R += parts[i];
        }
        assertEq(R, R0 + spend, "partitions must sum to the same reserve");
        assertEq(sum, bulk, "partition invariance: EXACT telescoping");

        // same property across a wave top (segment-boundary crossing)
        uint256 Rb = c.boot + c.span / 3 - 50e18; // straddles top-1 anchor
        uint256 bulk2 = SineMath.supplyAt(c, Rb + 300e18) - SineMath.supplyAt(c, Rb);
        uint256 sum2 = (SineMath.supplyAt(c, Rb + 100e18) - SineMath.supplyAt(c, Rb))
            + (SineMath.supplyAt(c, Rb + 300e18) - SineMath.supplyAt(c, Rb + 100e18));
        assertEq(sum2, bulk2, "boundary-crossing telescoping");
    }

    // ── round-trip strictness: sell(buy(x)) < x ──
    function test_RoundTrip_Strict() public view {
        uint256[6] memory spends = [uint256(0.01e18), 1e18, 25e18, 250e18, 2500e18, 7000e18];
        uint256[3] memory starts = [curve.boot, curve.boot + curve.span / 3, curve.boot + curve.span * 2 / 3];
        for (uint256 s = 0; s < starts.length; s++) {
            uint256 R = starts[s];
            for (uint256 i = 0; i < spends.length; i++) {
                uint256 out = SineMath.buyOut(curve, R, spends[i]);
                if (out == 0) continue;
                uint256 back = SineMath.sellOut(curve, R + spends[i], out);
                assertLt(back, spends[i], "round trip must lose");
            }
        }
    }

    // ── monotonicity at 45°: price never decreases ──
    function test_MonotonePrice_45Deg() public view {
        uint256 steps = 2400;
        uint256 prev = 0;
        for (uint256 i = 0; i <= steps; i++) {
            uint256 R = (curve.boot + curve.span + 2000e18) * i / steps;
            uint256 p = SineMath.priceAt(curve, R);
            assertGe(p, prev, "price must be non-decreasing at 45 deg tilt");
            prev = p;
        }
    }

    // ── boot invariance of the wave shape ──
    function test_BootInvariance_WaveShape() public pure {
        SineMath.Params memory p = SineMath.Params({
            p0: V.P0, preK: V.PREK, magM: V.MAGM, lnTop: V.LNTOP, ampBps: 10_000
        });
        SineMath.Curve memory a = SineMath.materialize(p, 500e18);
        SineMath.Curve memory b = SineMath.materialize(p, 1500e18);
        // pTop/B is a pure function of lnTop regardless of actual boot
        uint256 ra = a.pTop * 1e18 / a.B;
        uint256 rb = b.pTop * 1e18 / b.B;
        assertApproxEqRel(ra, rb, 1e12, "pTop/B boot-invariant");
        // wave-relative prices identical: p(boot + f·span)/B for f = 0.137…
        for (uint256 f = 1; f < 10; f++) {
            uint256 pa = SineMath.priceAt(a, a.boot + a.span * f / 10) * 1e18 / a.B;
            uint256 pb = SineMath.priceAt(b, b.boot + b.span * f / 10) * 1e18 / b.B;
            assertApproxEqRel(pa, pb, 1e12, "wave shape boot-invariant");
        }
    }

    // ── tail is linear with the trend slope at top ──
    function test_Tail_Linear() public view {
        uint256 top = curve.boot + curve.span;
        uint256 p0t = SineMath.priceAt(curve, top);
        uint256 p1t = SineMath.priceAt(curve, top + 777e18);
        // slope check: (p1−p0)/777e18 ≈ tailSlope (WAD) within rounding
        uint256 slope = (p1t - p0t) * 1e18 / 777e18;
        assertApproxEqRel(slope, curve.tailSlope, 1e12, "tail slope = trend");
    }

    // ── validate ──
    function test_Validate_RejectsOver45() public {
        SineCaller caller = new SineCaller();
        SineMath.Params memory p = SineMath.Params({
            p0: V.P0, preK: V.PREK, magM: V.MAGM, lnTop: V.LNTOP, ampBps: 10_001
        });
        vm.expectRevert(SineMath.InvalidParams.selector);
        caller.callValidate(p);
    }

    // ── gas profile (informational) ──
    function test_GasProfile() public view {
        uint256 g0 = gasleft();
        SineMath.buyOut(curve, curve.boot, 100e18);
        uint256 gBuy = g0 - gasleft();
        uint256 out = SineMath.buyOut(curve, curve.boot + curve.span / 2, 500e18);
        g0 = gasleft();
        SineMath.sellOut(curve, curve.boot + curve.span / 2 + 500e18, out);
        uint256 gSell = g0 - gasleft();
        console2.log("gas buyOut(100e18):", gBuy);
        console2.log("gas sellOut:", gSell);
    }
}
