/// Pixel-art icons — hand-drawn 24×24 grids in the pepe palette, rendered as
/// horizontal <rect> runs (same visual language as the on-chain RLE art).
/// shapeRendering="crispEdges" keeps every run pixel-sharp at any size.

type Grid = string[]

// letters are LOCAL to each grid — palettes below give them color
const ICONS: Record<string, Grid> = {
  // bonding curve: green axes, sky staircase, gold coin at the summit
  chart: [
    '........................',
    '........................',
    '..oo............oooooo..',
    '..oo............oyYYyo..',
    '..oo............oyYYyo..',
    '..oo............oyyyyo..',
    '..oo............oooooo..',
    '..oo..................o.',
    '..oo.........ooooo......',
    '..oo.........oSSSo......',
    '..oo.........oSsso......',
    '..oo.........oSsso......',
    '..oo.....ooooo..........',
    '..oo.....oSSSo..........',
    '..oo.....oSsso..........',
    '..oo.....oSsso..........',
    '..oo.ooooo..............',
    '..oo.oSSSo..............',
    '..oo.oSsso..............',
    '..oo.oSsso..............',
    '..aaaaaaaaaaaaaaaaaaaa..',
    '........................',
    '........................',
    '........................',
  ],
  // predeposit: ghost coin dropping into the big P-barred vault coin
  coin: [
    '........................',
    '.........ooooo..........',
    '........oLllllLo........',
    '.........ooooo..........',
    '........................',
    '.....oooooooooooo.......',
    '....oYYYYYYYYYYYYYo.....',
    '....oyyyyyyyyyyyyyyyo...',
    '....oyyyyddddyyyyo......',
    '....oyyyddddddyyyo......',
    '....oyyydddddyyyyo......',
    '....oyyyddddyyyyyo......',
    '....oyyyyddyyyyyyo......',
    '....oyyyyyyyyyyyyo......',
    '....oyyyyyyyyyyyyo......',
    '....oyyyyyyyyyyyyo......',
    '....oyyyyyyyyyyyyo......',
    '....oyyyyyyyyyyyyo......',
    '....oddddddddddddo......',
    '.....oooooooooooo.......',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // stake & earn: faceted gem, teal ramp, light girdle band, white sparks
  diamond: [
    '..................W.....',
    '................WWW.....',
    '..................W.....',
    '........................',
    '........oooooooo........',
    '......otGGGGGGGGto......',
    '.....otGGGGGGGGGGto.....',
    '....oGLLGGGGGGGGGGo.....',
    '...oGLLLGGGGGGGGGGGo....',
    '....ogGGGGGGGGGGgGo.....',
    '.....ogGGGGGGGGGgo......',
    '......ogGGGGGGgo........',
    '.......ogddddgo.........',
    '........oddddo..........',
    '.........oddo...........',
    '..........oo............',
    '........................',
    '....................W...',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // carpet bomb: black bomb, steel glint, rope fuse, spark star
  bomb: [
    '...................Yy...',
    '..................yWYy..',
    '...................Yy...',
    '........................',
    '................ww......',
    '...............ww.......',
    '..............oo........',
    '.............oooo.......',
    '......oooooooooo........',
    '.....okkkllkkkkkko......',
    '....okkkllkkkkkkkkko....',
    '....okkkllkkkkkkkkko....',
    '...okkkllkkkkkkkkkkko...',
    '...okkkllkkkkkkkkkkko...',
    '...okkkllkkkkkkkkkkko...',
    '...okkkkkkkkkkkkkkkko...',
    '...okkkkkkkkkkkkkkkko...',
    '....okkkkkkkkkkkkkko....',
    '....okkkkkkkkkkkkkko....',
    '.....okkkkkkkkkkkko.....',
    '......oooooooooooo......',
    '........................',
    '........................',
    '........................',
  ],
  // positive sum: sky + emerald discs overlapping, white plus at the seam
  sum: [
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '.........s.....g........',
    '......sssssssggggggg....',
    '....SSSSssggggGGgggggg..',
    '....SSSsssgggGGggggggg..',
    '....SSssssgggGGggggggg..',
    '...SSsssssgggWggggggggg.',
    '...SssssssggWWWgggggggg.',
    '...sssssssggWgggggggggg.',
    '...sssssssggggggggggggg.',
    '....ssssssgggggggggggg..',
    '....ssssssgggggggggggg..',
    '......ssssssggggggggg...',
    '.........s.....g........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // your keys: sky shield, gold keyhole
  shield: [
    '........................',
    '........................',
    '........................',
    '.......oooooooooo.......',
    '......oSSSSSSSSSSo......',
    '......oSSSSSSSSSSo......',
    '......osssssssssso......',
    '......osssssssssso......',
    '......ossyyyyssso.......',
    '......ossyyyyssso.......',
    '......ossyyyyssso.......',
    '......ossssyyssso.......',
    '......ossssyyssso.......',
    '......ossssyyssso.......',
    '......ossssssssso.......',
    '.......ossssssso........',
    '........ossssoo.........',
    '.........ossso..........',
    '..........oso...........',
    '...........o............',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // refresh: sky C-ring with a chunky arrowhead (randomize pepes)
  die: [
    '........................',
    '.....oooooooooooooo.....',
    '....owwwwwwwwwwwwwwo....',
    '....owwwwwwwwwwwwwwo....',
    '....owwppwwwwppwwwwo....',
    '....owwppwwwwppwwwwo....',
    '....owwwwwwwwwwwwwwo....',
    '....owwwwwwwwwwwwwwo....',
    '....owwwwwppwwwwwwwo....',
    '....owwwwwppwwwwwwwo....',
    '....owwwwwwwwwwwwwwo....',
    '....owwwwwwwwwwwwwwo....',
    '....owwppwwwwppwwwwo....',
    '....owwppwwwwppwwwwo....',
    '....owwwwwwwwwwwwwwo....',
    '....owwwwwwwwwwwwwwo....',
    '....oddddddddddddddo....',
    '.....oooooooooooooo.....',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // refresh: sky C-ring with a chunky arrowhead (relock / extend)
  refresh: [
    '........................',
    '........................',
    '........SSSSSSssssss....',
    '......SS......ssssss....',
    '.....S........sssssss...',
    '.....S........ssssss....',
    '.....S.........sssss....',
    '.....s..................',
    '.....s..................',
    '.....s..................',
    '.....s..................',
    '.....s..........ss......',
    '.....s..........ss......',
    '.....s..........ss......',
    '.....s..........ss......',
    '.....s..........ss......',
    '.....ssssssssssss.......',
    '......ssssssssss........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // withdraw: open padlock, lifted shackle, gold body
  unlock: [
    '........................',
    '........................',
    '........................',
    '.......wwwwwwwww........',
    '.......w.......w........',
    '.......w.......w........',
    '.......w.......ww.......',
    '.......w................',
    '.......w................',
    '.......w................',
    '.....oooooooooooooo.....',
    '....oyyyyyyyyyyyyyyyo...',
    '....oyyyyyyyyyyyyyyyo...',
    '....oyyyyyddddyyyyyo....',
    '....oyyyyyddddyyyyyo....',
    '....oyyyyyyddyyyyyyo....',
    '....oyyyyyyddyyyyyyo....',
    '....oyyyyyyddyyyyyyo....',
    '....oddddddddddddddo....',
    '.....oooooooooooooo.....',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // faucet: round water droplet with sky glint
  droplet: [
    '........................',
    '........................',
    '........................',
    '...........oo...........',
    '..........oSso..........',
    '.........oSSsso.........',
    '........oSSssssso.......',
    '.......oSSssssssso......',
    '......oSSssssssssso.....',
    '.....oSSsssssssssssso...',
    '.....osSSssssssssssso...',
    '.....osssssssssssssso...',
    '.....osssssssssssssso...',
    '.....osssssssssssssso...',
    '......ossssssssssso.....',
    '.......osssssssso.......',
    '........osssssso........',
    '.........ossso..........',
    '..........osso..........',
    '...........oo...........',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // choose your pepe: cream palette board with paint pips + thumb hole
  palette: [
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........oooooooooo......',
    '......oowwwwwwwwwwoo....',
    '.....owwwwwwwwwwwwwwo...',
    '....owwwwwrrwwyywwwo....',
    '....owwwwrrwwyywwwwwo...',
    '....owwggwwsswwwwwwwo...',
    '....owwggwwsswwwwwwwo...',
    '....owwwwwwwwwwwwwwwo...',
    '....owwwwwwwwwwwwwwwo...',
    '....owwwwwwwwwwwwwwwo...',
    '....owwwwooowwwwwwwo....',
    '....owwwooowwwwwwwwo....',
    '.....owwwwwwwwwwwwwo....',
    '......owwwwwwwwwwwo.....',
    '........oooooooooo......',
    '........................',
    '........................',
    '........................',
  ],
}

// letter -> fill, per icon (deep shades — icons sit on bright gradient tiles)
const PALETTES: Record<string, Record<string, string>> = {
  chart: { a: '#14532D', o: '#0F172A', S: '#7DD3FC', s: '#0369A1', Y: '#FDE68A', y: '#D97706' },
  coin: { o: '#7C5A16', Y: '#FDE68A', y: '#E8B93E', d: '#8C6A1D', L: '#FEF9C3', l: '#F7E7A8' },
  diamond: { o: '#134E4A', t: '#5EEAD4', G: '#2DD4BF', g: '#14B8A6', d: '#0F766E', L: '#CCFBF1', W: '#FFFFFF' },
  bomb: { o: '#0B0F14', k: '#2A3138', l: '#9AA7B8', w: '#8C6A1D', Y: '#FDE68A', y: '#F59E0B', W: '#FFFFFF' },
  sum: { S: '#7DD3FC', s: '#0EA5E9', G: '#6EE7B7', g: '#10B981', W: '#FFFFFF' },
  shield: { o: '#0C4A6E', S: '#7DD3FC', s: '#38BDF8', y: '#E8B93E' },
  die: { o: '#334155', w: '#F8FAFC', p: '#1E293B', d: '#CBD5E1' },
  refresh: { S: '#7DD3FC', s: '#0369A1' },
  unlock: { o: '#7C5A16', y: '#E8B93E', d: '#8C6A1D', w: '#94A3B8' },
  droplet: { o: '#0C4A6E', S: '#BAE6FD', s: '#0EA5E9' },
  palette: { o: '#334155', w: '#FEF3C7', r: '#DC2626', y: '#F59E0B', g: '#16A34A', s: '#0284C7' },
}

export function PixelIcon({ name, size = 22 }: { name: string; size?: number }) {
  const rows = ICONS[name]
  const pal = PALETTES[name]
  if (!rows || !pal) return null
  const runs: { x: number; y: number; w: number; fill: string }[] = []
  rows.forEach((row, y) => {
    let x = 0
    while (x < row.length) {
      const ch = row[x]
      if (ch === '.') {
        ++x
        continue
      }
      let w = 1
      while (x + w < row.length && row[x + w] === ch) ++w
      runs.push({ x, y, w, fill: pal[ch] ?? '#f0f' })
      x += w
    }
  })
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      shapeRendering="crispEdges"
      aria-hidden="true"
      className="inline-block shrink-0 align-[-0.28em]"
    >
      {runs.map((r, i) => (
        <rect key={i} x={r.x} y={r.y} width={r.w} height={1} fill={r.fill} />
      ))}
    </svg>
  )
}
