#!/usr/bin/env python3
"""Generate the hook proof fixture from a real constructor execution.

Run Forge's test_export_runtime_fixture first, then this script, then rebuild
and run test_fixture_matches_constructor before Halmos. The Solidity fixture
must match the real constructor byte for byte. No production code is rewritten.
"""
import argparse
import hashlib
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime", default="out/hook-rules-runtime.hex")
    parser.add_argument("--artifact", default="out/HookRulesSymbolic.t.sol/HookRulesHarness.json")
    parser.add_argument("--output", default="test/dinosat/HookRulesRuntime.sol")
    args = parser.parse_args()
    artifact = json.loads(Path(args.artifact).read_text())
    deployed = artifact["deployedBytecode"]
    template = bytes.fromhex(deployed["object"].removeprefix("0x"))
    actual = bytes.fromhex(Path(args.runtime).read_text().strip().removeprefix("0x"))
    if len(actual) != len(template):
        raise SystemExit("Runtime length differs from the compiler artifact")
    # Exact known immutable values from HookRulesHarness's real constructor.
    expected = {0x1111, 0xC0FFEE, 0x2222, 0x3333, 248_660}
    seen = set()
    normalized = bytearray(actual)
    references = deployed["immutableReferences"]
    if len(references) != len(expected):
        raise SystemExit("Unexpected immutable count; review the harness constructor")
    for locations in references.values():
        values = set()
        for location in locations:
            start, length = location["start"], location["length"]
            if length != 32 or start + length > len(actual):
                raise SystemExit("Invalid immutable reference")
            values.add(int.from_bytes(actual[start:start + length], "big"))
            normalized[start:start + length] = template[start:start + length]
        if len(values) != 1 or not values.issubset(expected):
            raise SystemExit(f"Unexpected or inconsistent immutable value: {values}")
        seen.update(values)
    if seen != expected or bytes(normalized) != template:
        raise SystemExit("Runtime differs outside immutable slots or an immutable is missing")
    digest = hashlib.sha256(actual).hexdigest()
    source = (
        '// SPDX-License-Identifier: MIT\npragma solidity 0.8.26;\n\n'
        '/// @title Exact constructor runtime for the hook symbolic harness\n'
        '/// @notice Generated by scripts/formal/generate_hook_fixture.py.\n'
        '/// Forge test_fixture_matches_constructor checks byte identity.\n'
        f'/// SHA-256: {digest}\n'
        'library HookRulesRuntime {\n'
        '    function code() internal pure returns (bytes memory) {\n'
        f'        return hex"{actual.hex()}";\n'
        '    }\n}\n'
    )
    Path(args.output).write_text(source)
    print(f"Wrote {args.output}: {len(actual)} bytes, sha256 {digest}")


if __name__ == "__main__":
    main()
