import test from 'node:test';
import assert from 'node:assert/strict';
import { createCurve, priceAt, supplyAt, sampleCurve, estimateBuy } from './curve.js';

const close = (actual, expected, tolerance = 1e-10) => {
  assert.ok(Number.isFinite(actual), `nonfinite result ${actual}`);
  assert.ok(Math.abs(actual - expected) <= Math.max(1e-14, Math.abs(expected) * tolerance),
    `${actual} differs from ${expected}`);
};

// Independent 60-digit Decimal / Simpson oracle, scripts/sine_oracle.py.
// Boot900, full amplitude. These are not generated by the prototype implementation.
const ORACLE = [[900.0, 7.4999999999999e-05, 38711540.5579213], [2491.6666666666665, 9.1827280297121e-05, 58876737.86189846], [4083.3333333333335, 0.000228512306841762, 70822406.60389815], [5675.0, 0.000568653173753862, 75185348.18174477], [7266.666666666667, 0.000696238325041916, 77599486.79577279], [13633.333333333334, 0.00646330407009565, 81788563.8157223], [20000.0, 0.06, 82239818.45826827], [26366.666666666668, 0.5569906600335335, 82288428.39106558]];

test('launch seam, quarter waves and target match independent price and supply vectors', () => {
  const curve = createCurve(900);
  close(priceAt(curve, 0), 0.00001);
  assert.equal(supplyAt(curve, 0), 0);
  for (const [reserve, price, supply] of ORACLE) {
    close(priceAt(curve, reserve), price, 1e-11);
    close(supplyAt(curve, reserve), supply, 1e-9);
  }
  close(curve.lam * 3 + curve.boot, 20_000);
  close(curve.amp * 2 * Math.PI, curve.slope * curve.lam);
});

test('curve scale follows the IBCO while launch and third-wave prices stay fixed', () => {
  const reference = createCurve(450);
  for (const boot of [1e-18, .0045, 450, 900, 9000, 1e6, 1e12, 1e18]) {
    const curve = createCurve(boot);
    close(curve.B, 0.000075);
    close(curve.targetReserve, boot * 10000 / 450);
    close(priceAt(curve, curve.targetReserve) / curve.B, 800);
    close(curve.q0 / boot, reference.q0 / 450);
    for (const wave of [0, .5, 1, 2, 3]) {
      const r = curve.boot + curve.lam * wave;
      close(priceAt(curve, r), priceAt(reference, reference.boot + reference.lam * wave));
      close(supplyAt(curve, r) / boot, supplyAt(reference, reference.boot + reference.lam * wave) / 450);
    }
  }
});

test('chart uses the same curve through launch and successive waves, with monotone geometry', () => {
  const curve = createCurve();
  const chart = sampleCurve(curve, 1248.36);
  assert.equal(chart.truncated, false);
  assert.ok(chart.end >= 1248.36 + curve.lam);
  assert.equal(chart.livePoint.reserve, 1248.36);
  close(chart.livePoint.price, priceAt(curve, 1248.36));
  assert.ok(chart.points.some(point => point.reserve === curve.boot));
  assert.ok(chart.points.some(point => point.reserve === curve.targetReserve));
  close(chart.markers.find(marker => marker.k === 12).price, 0.06);
  for (let i = 1; i < chart.points.length; i++) {
    const a = chart.points[i - 1], b = chart.points[i];
    assert.ok(b.reserve > a.reserve);
    assert.ok(b.price >= a.price * (1 - 1e-12));
    assert.ok(b.supply >= a.supply * (1 - 1e-12));
  }
  close(priceAt(curve, 900 - 1e-7), priceAt(curve, 900 + 1e-7), 1e-9);
});

test('chart extends with real wave headroom as demo reserves grow', () => {
  const curve = createCurve();
  let last = 0;
  for (const reserve of [1248.36, 20_000, 50_000, 100_000]) {
    const chart = sampleCurve(curve, reserve);
    assert.equal(chart.truncated, false);
    assert.ok(chart.end >= last);
    assert.ok(chart.end >= reserve + Math.max(curve.lam, 1000, reserve * 0.1));
    close(chart.points.at(-1).price,
      curve.B * Math.exp(curve.slope * (chart.end - curve.boot)));
    last = chart.end;
  }
});

test('extreme reserves keep geometry finite and bounded without inventing a capped live price', () => {
  const curve = createCurve();
  for (const reserve of [1e6, 1e7, 1e12, 1e59]) {
    const chart = sampleCurve(curve, reserve);
    assert.equal(chart.truncated, true);
    assert.equal(chart.livePoint, null);
    assert.ok(chart.points.length <= 8270);
    assert.ok(chart.end < reserve);
    chart.points.forEach(point => assert.ok([point.reserve, point.price, point.supply, point.price * 1e18].every(Number.isFinite)));
  }
  assert.equal(priceAt(curve, 1e7), null);
  assert.equal(supplyAt(curve, 1e7), null);
});

// Separate dense Simpson integration checks the bounded GL8 buy estimate.
function simpsonBuy(curve, start, spend) {
  const n = 16384, step = spend / n;
  const density = reserve => 1 / priceAt(curve, reserve);
  let sum = density(start) + density(start + spend);
  for (let i = 1; i < n; i++) sum += (i % 2 ? 4 : 2) * density(start + step * i);
  return sum * step / 3 * 0.9999;
}

test('buy estimate integrates changing price after fees and applies the PSP output haircut', () => {
  const curve = createCurve();
  for (const [reserve, net] of [[1248.36, 0.009], [1248.36, 90], [1248.36, 10_000], [850, 100]]) {
    close(estimateBuy(curve, reserve, net), simpsonBuy(curve, reserve, net), 1e-8);
  }
  close(estimateBuy(curve, 1248.36, 0.009), 119.70185823202551, 1e-10);
  assert.ok(estimateBuy(curve, 1248.36, 10_000) < 10_000 / priceAt(curve, 1248.36));
  assert.equal(estimateBuy(curve, 1248.36, 0), 0);
});

test('invalid and unsupported quotes are explicit and cannot reach an Infinity-to-BigInt conversion', () => {
  const curve = createCurve();
  for (const [reserve, amount] of [[1248.36, 1e7], [1e7, 0.005], [Infinity, 1],
    [0, Infinity], [NaN, 1], [-1, 1], [100, -1], [1e59, 1e59]]) {
    assert.equal(estimateBuy(curve, reserve, amount), null);
  }
  for (const reserve of [Infinity, NaN, -1]) {
    assert.equal(priceAt(curve, reserve), null);
    assert.throws(() => sampleCurve(curve, reserve), /Invalid live reserve/);
  }
  for (const boot of [0, -1, NaN, Infinity, Number.MAX_VALUE]) {
    assert.throws(() => createCurve(boot), RangeError);
  }
});
