// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {CurveMath} from "../libraries/CurveMath.sol";

/// @title curve2 — sharkfin — GENERATED by ~/clawd/psp-rolling.py (2026-08-23). DO NOT HAND-EDIT.
/// @notice 6 teeth (2/decade, BIG): exp ramp on 25% of leg reserve, log runway at k2=0.25 (hardest legal flip). Warm-up glide. Pure envelope (no weave).
///         Envelope P = 1e-3*(R/2000)^1.660964 — anchors (2000,1e-3) (8000,1e-2)
///         (32000,1e-1) (128000,1) hit exactly. Seed shelf + tail identical to
///         curvePrototype (LinearZones). 16 zones, S_end 7.08664e+06 PSP.
///         Forge-verified: 4/4 anchors <=2e-6 rel, forge-vs-float max dev 6.7e-10, monotone, smoothness 68.7°/step max vs prototype 85.6°.
///         Regenerate: `python3 ~/clawd/psp-rolling.py` (rewrites Curve[123]Zones.sol
///         + test/CurveDumpRolling.t.sol + frontend/src/lib/curveConfigs.json).
library Curve2Zones {
    uint256 internal constant P0_WAD = 100000000000000;

    function config() internal pure returns (CurveMath.CurveConfig memory) {
        uint256[] memory b = new uint256[](16);
        b[0] = 0;
        b[1] = 510512625000000010584064;
        b[2] = 2120338506131996971892736;
        b[3] = 5187725977033414113492992;
        b[4] = 5457256372556227707666432;
        b[5] = 5936466626714307831791616;
        b[6] = 6106042397088286500716544;
        b[7] = 6407826056344963813212160;
        b[8] = 6514769537551930224541696;
        b[9] = 6705183732271361726349312;
        b[10] = 6772709003081169936318464;
        b[11] = 6892971666068378828668928;
        b[12] = 6935636085776585070739456;
        b[13] = 7011633808424637231529984;
        b[14] = 7038600793655741916381184;
        b[15] = 7086641525536812976570368;

        uint256[] memory r = new uint256[](16);
        r[0] = 1958814;
        r[1] = 589231110992;
        r[2] = 441426006136;
        r[3] = 4194216698053;
        r[4] = 250000000000000000;
        r[5] = 6718556449935;
        r[6] = 250000000000000000;
        r[7] = 10698324716644;
        r[8] = 250000000000000000;
        r[9] = 16984780677093;
        r[10] = 250000000000000000;
        r[11] = 26921068332446;
        r[12] = 250000000000000000;
        r[13] = 42629661664140;
        r[14] = 250000000000000000;
        r[15] = 100000000000000000;

        bool[] memory e = new bool[](16);
        e[0] = true;
        e[1] = true;
        e[2] = true;
        e[3] = true;
        e[4] = false;
        e[5] = true;
        e[6] = false;
        e[7] = true;
        e[8] = false;
        e[9] = true;
        e[10] = false;
        e[11] = true;
        e[12] = false;
        e[13] = true;
        e[14] = false;
        e[15] = false;

        return CurveMath.multiCurve(P0_WAD, b, r, e);
    }
}
