// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {CurveMath} from "../libraries/CurveMath.sol";

/// @title curve1 — sawtooth — GENERATED by ~/clawd/psp-rolling.py (2026-08-23). DO NOT HAND-EDIT.
/// @notice 12 teeth (4/decade): exp ramp on 35% of leg reserve, log runway at k2=0.5 levels off. Warm-up glide. Pure envelope (no weave).
///         Envelope P = 1e-3*(R/2000)^1.660964 — anchors (2000,1e-3) (8000,1e-2)
///         (32000,1e-1) (128000,1) hit exactly. Seed shelf + tail identical to
///         curvePrototype (LinearZones). 30 zones, S_end 7.68449e+06 PSP.
///         Forge-verified: 4/4 anchors <=2e-6 rel, forge-vs-float max dev 6.7e-10, monotone, smoothness 58.2°/step max vs prototype 85.6°.
///         Regenerate: `python3 ~/clawd/psp-rolling.py` (rewrites Curve[123]Zones.sol
///         + test/CurveDumpRolling.t.sol + frontend/src/lib/curveConfigs.json).
library Curve1Zones {
    uint256 internal constant P0_WAD = 100000000000000;

    function config() internal pure returns (CurveMath.CurveConfig memory) {
        uint256[] memory b = new uint256[](30);
        b[0] = 0;
        b[1] = 510512625000000010584064;
        b[2] = 1143118297475331970301952;
        b[3] = 2156886275117723697545216;
        b[4] = 3573966408326702344175616;
        b[5] = 5301814704124618325622784;
        b[6] = 5519424456226966563979264;
        b[7] = 5826236425086411202363392;
        b[8] = 5998633675897691543961600;
        b[9] = 6241801135654182588514304;
        b[10] = 6378538225967110253707264;
        b[11] = 6571459959533271850680320;
        b[12] = 6679994056537509820628992;
        b[13] = 6833153559965283081256960;
        b[14] = 6919345161320143960145920;
        b[15] = 7040992362724194498117632;
        b[16] = 7109465028403476685651968;
        b[17] = 7206114178078974108762112;
        b[18] = 7260524370070562939076608;
        b[19] = 7337330111008789908946944;
        b[20] = 7380574012298795908333568;
        b[21] = 7441620828958361808535552;
        b[22] = 7475994869051349522186240;
        b[23] = 7524522342262175380275200;
        b[24] = 7551848756025223691632640;
        b[25] = 7590428058333430459400192;
        b[26] = 7612153579821208128454656;
        b[27] = 7642826371743900808249344;
        b[28] = 7660100064776265138176000;
        b[29] = 7684488120277192656551936;

        uint256[] memory r = new uint256[](30);
        r[0] = 1958814;
        r[1] = 589488026143;
        r[2] = 501168429498;
        r[3] = 453907669858;
        r[4] = 450490114899;
        r[5] = 2522666365821;
        r[6] = 500000000000000000;
        r[7] = 3224950183308;
        r[8] = 500000000000000000;
        r[9] = 4101722725816;
        r[10] = 500000000000000000;
        r[11] = 5199982756890;
        r[12] = 500000000000000000;
        r[13] = 6578019427164;
        r[14] = 500000000000000000;
        r[15] = 8308680950712;
        r[16] = 500000000000000000;
        r[17] = 10483303894306;
        r[18] = 500000000000000000;
        r[19] = 13216571188667;
        r[20] = 500000000000000000;
        r[21] = 16652579348949;
        r[22] = 500000000000000000;
        r[23] = 20972445393380;
        r[24] = 500000000000000000;
        r[25] = 26403859421406;
        r[26] = 500000000000000000;
        r[27] = 33233088823593;
        r[28] = 500000000000000000;
        r[29] = 100000000000000000;

        bool[] memory e = new bool[](30);
        e[0] = true;
        e[1] = true;
        e[2] = true;
        e[3] = true;
        e[4] = true;
        e[5] = true;
        e[6] = false;
        e[7] = true;
        e[8] = false;
        e[9] = true;
        e[10] = false;
        e[11] = true;
        e[12] = false;
        e[13] = true;
        e[14] = false;
        e[15] = true;
        e[16] = false;
        e[17] = true;
        e[18] = false;
        e[19] = true;
        e[20] = false;
        e[21] = true;
        e[22] = false;
        e[23] = true;
        e[24] = false;
        e[25] = true;
        e[26] = false;
        e[27] = true;
        e[28] = false;
        e[29] = false;

        return CurveMath.multiCurve(P0_WAD, b, r, e);
    }
}
