// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {CurveMath} from "../libraries/CurveMath.sol";

/// @title LinearZonesLean — GENERATED by ~/clawd/psp-linear.py (2026-08-28). DO NOT HAND-EDIT.
/// @notice Anchor-ladder curve (scoopy anchors, 2026-08-19): N=4 S-legs, one
///         price decade per x4 reserve — P 0.0001 -> 1 over
///         2000 -> 128000 mixETH (checkpoints hit exactly).
///         Dials: DECADES=4, LSEG=1, MDEC=1, SHELF_T=40 (auto-grows to 40),
///         PSI 0.35->0.15, K2 0.56->0.92, ISL=0.35,
///         uniform per-leg lift Q=10.0000, budget 1e+08 (curve mints 3.78082e+06).
///         Cliffs 4.7896->9.7696, islands 35% of every span.
///         Forge-verified: anchors <=1e-6 rel, islands 4/4 exact, 333 samples.
///         Regenerate: `LSEG=1 MDEC=1 python3 ~/clawd/psp-linear.py` (rewrites
///         this file + the harness; then rename LinearZones->LinearZonesLean).
///         Why lean: Sepolia's 2^24 per-tx gas cap — the canonical 34-zone
///         ladder measures 29.5M in deployRound and can never deploy OR
///         rebirth there (spawnNextRound is single-tx). This 10-zone variant
///         keeps the anchor envelope exactly; steps are chunkier (4 legs).
library LinearZonesLean {
    uint256 internal constant P0_WAD = 100000000000000;

    function config() internal pure returns (CurveMath.CurveConfig memory) {
        uint256[] memory b = new uint256[](10);
        b[0] = 0;
        b[1] = 399999999999999966445568;
        b[2] = 400400000000000029360128;
        b[3] = 2793566240731502441660416;
        b[4] = 2796359806972232927805440;
        b[5] = 3432992005126366320132096;
        b[6] = 3436424997131493608259584;
        b[7] = 3681455631583184573956096;
        b[8] = 3685137087214768613228544;
        b[9] = 3780818109935308710608896;

        uint256[] memory r = new uint256[](10);
        r[0] = 2499999;
        r[1] = 3916111615080530;
        r[2] = 560000000000000064;
        r[3] = 777506331802322;
        r[4] = 680000000000000000;
        r[5] = 655098634883468;
        r[6] = 800000000000000000;
        r[7] = 619123794203880;
        r[8] = 920000000000000128;
        r[9] = 100000000000000000;

        bool[] memory e = new bool[](10);
        e[0] = true;
        e[1] = true;
        e[2] = false;
        e[3] = true;
        e[4] = false;
        e[5] = true;
        e[6] = false;
        e[7] = true;
        e[8] = false;
        e[9] = false;

        return CurveMath.multiCurve(P0_WAD, b, r, e);
    }
}
