// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Script, console} from "forge-std/Script.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {IPoolManager} from "@uniswap/v4-core/src/interfaces/IPoolManager.sol";

import {PSPFactory} from "../src/PSPFactory.sol";
import {HookDeployer} from "../src/HookDeployer.sol";
import {ControllerDeployer} from "../src/ControllerDeployer.sol";
import {CurveMath} from "../src/libraries/CurveMath.sol";
import {PSPZapIn} from "../src/PSPZapIn.sol";
import {PSPZapOut} from "../src/PSPZapOut.sol";
import {IMixETH} from "../src/interfaces/IMixETH.sol";

import {MockMixETH} from "../test/mocks/MockMixETH.sol";
import {MockPoolManager} from "../test/mocks/MockPoolManager.sol";

/// @title DeployPSP — genesis deployment with the housestyle curve
/// @notice Deploys the factory, round 1 ("Positive Sum Pepes" / PSP), and
///         publishes the walk-away UI via factory.setHtml(). The UI source is
///         script/app.html with __FACTORY__ substituted for the real address.
///
///         The curve is the optimizer's "housestyle" preset (max-min robust
///         across hot/neutral/cold/stillborn attention scenarios, seed sized
///         for scoopy's ~9000 PSP opening position):
///           N1=11, N2=12, M1=3.6, 48 zones, P0=4.31e-10, S_end=1e8,
///           island field = 0.385, tailK=0.3
///         Zone literals generated by ~/clawd/psp-zones-export.py — regenerate
///         there, don't hand-edit.
///
/// Env:
///   PSP_PM       pool manager (default: Base mainnet v4; REQUIRED with PSP_TESTNET)
///   PSP_MIXETH   mixETH token (required unless PSP_ANVIL/PSP_TESTNET)
///   PSP_HTML     ui file (default: script/app.html)
///   PSP_ANVIL    =1 to deploy MockMixETH+MockPoolManager first (local e2e)
///   PSP_TESTNET  =1 to deploy MockMixETH against a canonical v4 testnet
///                PoolManager + fast timing profile (24h predeposit offer,
///                3d stake lock, +1d relock, 1d bomb vote; flat exit 3d)
contract DeployPSP is Script {
    // Base mainnet Uniswap v4 PoolManager
    address constant PM_BASE = 0x498581fF718922c3f8e6A244956aF099B2652b2b;

    // Official v4 testnet PoolManagers (Uniswap deployments feed, verified
    // on-chain 2026-08-18 via eth_getCode — 24009 bytes each)
    address constant PM_SEPOLIA = 0xE03A1074c86CFeDd5C142C4F04F1a1536e203543;      // 11155111
    address constant PM_BASE_SEPOLIA = 0x05E73354cFDd6745C338b50BcFDfA3Aa6fA03408; // 84532
    address constant PM_ARB_SEPOLIA = 0xFB3e0C6F74eB1a21CC1Da29aeC80D2Dfe6C9a317;  // 421614
    address constant PM_UNICHAIN_SEPOLIA = 0x9cB26A7183B2F4515945Dc52CB4195B0d2D06C95; // 1301

    /// @dev Packed testnet timing profile (see RoundController "Timing profile"):
    ///      [0]=24h predeposit offer · [64]=3d lock · [128]=+1d relock
    ///      [192]=1d relock window · [256]=1d bomb vote. Flat exit: constant 3d.
    function _testnetTimings() internal pure returns (uint256) {
        return uint256(1 days) | (uint256(3 days) << 64) | (uint256(1 days) << 128)
            | (uint256(1 days) << 192) | (uint256(1 days) << 256);
    }

    function run() external {
        bool anvil = vm.envOr("PSP_ANVIL", false);
        bool testnet = vm.envOr("PSP_TESTNET", false);
        address pm;
        IERC20 mix;
        if (anvil) {
            vm.startBroadcast();
            MockPoolManager mockPM = new MockPoolManager();
            MockMixETH mockMix = new MockMixETH();
            vm.stopBroadcast();
            pm = address(mockPM);
            mix = IERC20(address(mockMix));
            console.log("ANVIL mock mixETH:", address(mockMix));
        } else if (testnet) {
            // Canonical v4 PoolManager of the target testnet — no default:
            // pass PSP_PM explicitly (constants above for copy-paste).
            pm = vm.envAddress("PSP_PM");
            vm.startBroadcast();
            MockMixETH mockMix = new MockMixETH();
            vm.stopBroadcast();
            mix = IERC20(address(mockMix));
            console.log("TESTNET PoolManager:", pm);
            console.log("TESTNET mock mixETH:", address(mockMix));
        } else {
            pm = vm.envOr("PSP_PM", PM_BASE);
            mix = IERC20(vm.envAddress("PSP_MIXETH"));
        }
        string memory htmlPath = vm.envOr("PSP_HTML", string("script/app.html"));

        vm.startBroadcast();
        PSPFactory factory = new PSPFactory(
            IPoolManager(pm), mix, new HookDeployer(), new ControllerDeployer(), testnet ? _testnetTimings() : 0
        );

        (uint256 roundId, address hookAddr) = factory.deployRound(_housestyleParams());

        // publish the walk-away UI (fetch factory.html() from any rpc)
        string memory h = vm.readFile(htmlPath);
        h = vm.replace(h, "__FACTORY__", vm.toString(address(factory)));
        factory.setHtml(h);

        // quality-of-life routers: ETH <-> PSP round trip
        PSPZapIn zapIn = new PSPZapIn(IMixETH(address(mix)), IPoolManager(pm));
        PSPZapOut zapOut = new PSPZapOut(IMixETH(address(mix)), IPoolManager(pm));
        vm.stopBroadcast();

        console.log("factory:", address(factory));
        console.log("round 1 id:", roundId);
        console.log("hook:", hookAddr);
        console.log("zapIn:", address(zapIn));
        console.log("zapOut:", address(zapOut));
        console.log("ui bytes:", bytes(h).length);
    }

    function _housestyleParams() internal pure returns (PSPFactory.RoundParams memory) {
        CurveMath.Zone[48] memory zs = [
            CurveMath.Zone({startSupply: 0, endSupply: 9000002655525880725504, rate: 111111022, isExponential: true}), // seed
            CurveMath.Zone({startSupply: 9000002655525880725504, endSupply: 11653330403185997643776, rate: 482765028403173, isExponential: true}), // s1 cliff
            CurveMath.Zone({startSupply: 11653330403185997643776, endSupply: 16525189346694153633792, rate: 438568450861384640, isExponential: false}), // s1 tread
            CurveMath.Zone({startSupply: 16525189346694153633792, endSupply: 21397048290202313818112, rate: 262925068298402, isExponential: true}), // s2 cliff
            CurveMath.Zone({startSupply: 21397048290202313818112, endSupply: 30342422485445086543872, rate: 438568450861384640, isExponential: false}), // s2 tread
            CurveMath.Zone({startSupply: 30342422485445086543872, endSupply: 39287796680687863463936, rate: 143195110400554, isExponential: true}), // s3 cliff
            CurveMath.Zone({startSupply: 39287796680687863463936, endSupply: 55712680984767117656064, rate: 438568450861384640, isExponential: false}), // s3 tread
            CurveMath.Zone({startSupply: 55712680984767117656064, endSupply: 72137565288846380236800, rate: 77987389241087, isExponential: true}), // s4 cliff
            CurveMath.Zone({startSupply: 72137565288846380236800, endSupply: 102295814515117856391168, rate: 438568450861384640, isExponential: false}), // s4 tread
            CurveMath.Zone({startSupply: 102295814515117856391168, endSupply: 132454063741389340934144, rate: 42473746929122, isExponential: true}), // s5 cliff
            CurveMath.Zone({startSupply: 132454063741389340934144, endSupply: 187828578383663984541696, rate: 438568450861384640, isExponential: false}), // s5 tread
            CurveMath.Zone({startSupply: 187828578383663984541696, endSupply: 243203093025938644926464, rate: 23132190931821, isExponential: true}), // s6 cliff
            CurveMath.Zone({startSupply: 243203093025938644926464, endSupply: 344877989630889433235456, rate: 438568450861384640, isExponential: false}), // s6 tread
            CurveMath.Zone({startSupply: 344877989630889433235456, endSupply: 446552886235840255098880, rate: 12598329462178, isExponential: true}), // s7 cliff
            CurveMath.Zone({startSupply: 446552886235840255098880, endSupply: 633241377618756089413632, rate: 438568450861384640, isExponential: false}), // s7 tread
            CurveMath.Zone({startSupply: 633241377618756089413632, endSupply: 819929869001671789510656, rate: 6861343385301, isExponential: true}), // s8 cliff
            CurveMath.Zone({startSupply: 819929869001671789510656, endSupply: 1162714508854769609605120, rate: 438568450861384640, isExponential: false}), // s8 tread
            CurveMath.Zone({startSupply: 1162714508854769609605120, endSupply: 1505499148707867698135040, rate: 3736847269501, isExponential: true}), // s9 cliff
            CurveMath.Zone({startSupply: 1505499148707867698135040, endSupply: 2134896860633300132167680, rate: 438568450861384640, isExponential: false}), // s9 tread
            CurveMath.Zone({startSupply: 2134896860633300132167680, endSupply: 2764294572558732566200320, rate: 2035173978538, isExponential: true}), // s10 cliff
            CurveMath.Zone({startSupply: 2764294572558732566200320, endSupply: 3919951605343918684635136, rate: 438568450861384640, isExponential: false}), // s10 tread
            CurveMath.Zone({startSupply: 3919951605343918684635136, endSupply: 5075608638129105339940864, rate: 1108403106737, isExponential: true}), // s11 cliff
            CurveMath.Zone({startSupply: 5075608638129105339940864, endSupply: 7197547043879280466460672, rate: 438568450861384640, isExponential: false}), // s11 tread
            CurveMath.Zone({startSupply: 7197547043879280466460672, endSupply: 8637056452655136989249536, rate: 2274523717, isExponential: true}), // s12 cliff
            CurveMath.Zone({startSupply: 8637056452655136989249536, endSupply: 8952081111369231565324288, rate: 438568450861384640, isExponential: false}), // s12 tread
            CurveMath.Zone({startSupply: 8952081111369231565324288, endSupply: 10742497333643077448892416, rate: 1662972690, isExponential: true}), // s13 cliff
            CurveMath.Zone({startSupply: 10742497333643077448892416, endSupply: 11136623257105490979586048, rate: 438568450861384640, isExponential: false}), // s13 tread
            CurveMath.Zone({startSupply: 11136623257105490979586048, endSupply: 13363947908526588746006528, rate: 1203522926, isExponential: true}), // s14 cliff
            CurveMath.Zone({startSupply: 13363947908526588746006528, endSupply: 13857122966188040155824128, rate: 438568450861384640, isExponential: false}), // s14 tread
            CurveMath.Zone({startSupply: 13857122966188040155824128, endSupply: 16628547559425645610008576, rate: 860159535, isExponential: true}), // s15 cliff
            CurveMath.Zone({startSupply: 16628547559425645610008576, endSupply: 17245771867896153808830464, rate: 438568450861384640, isExponential: false}), // s15 tread
            CurveMath.Zone({startSupply: 17245771867896153808830464, endSupply: 20694926241475385429590016, rate: 605106666, isExponential: true}), // s16 cliff
            CurveMath.Zone({startSupply: 20694926241475385429590016, endSupply: 21467537292481133409206272, rate: 438568450861384640, isExponential: false}), // s16 tread
            CurveMath.Zone({startSupply: 21467537292481133409206272, endSupply: 25761044750977354078093312, rate: 416990849, isExponential: true}), // s17 cliff
            CurveMath.Zone({startSupply: 25761044750977354078093312, endSupply: 26728330845358835472793600, rate: 438568450861384640, isExponential: false}), // s17 tread
            CurveMath.Zone({startSupply: 26728330845358835472793600, endSupply: 32073997014430606862319616, rate: 279405465, isExponential: true}), // s18 cliff
            CurveMath.Zone({startSupply: 32073997014430606862319616, endSupply: 33285223234285911565926400, rate: 438568450861384640, isExponential: false}), // s18 tread
            CurveMath.Zone({startSupply: 33285223234285911565926400, endSupply: 39942267881143093879111680, rate: 179790197, isExponential: true}), // s19 cliff
            CurveMath.Zone({startSupply: 39942267881143093879111680, endSupply: 41459220536081957448056832, rate: 438568450861384640, isExponential: false}), // s19 tread
            CurveMath.Zone({startSupply: 41459220536081957448056832, endSupply: 49751064643298338629746688, rate: 108557563, isExponential: true}), // s20 cliff
            CurveMath.Zone({startSupply: 49751064643298338629746688, endSupply: 51651247446933323116445696, rate: 438568450861384640, isExponential: false}), // s20 tread
            CurveMath.Zone({startSupply: 51651247446933323116445696, endSupply: 61981496936319982585774080, rate: 58413054, isExponential: true}), // s21 cliff
            CurveMath.Zone({startSupply: 61981496936319982585774080, endSupply: 64362146565100449900265472, rate: 438568450861384640, isExponential: false}), // s21 tread
            CurveMath.Zone({startSupply: 64362146565100449900265472, endSupply: 77234575878120538162331648, rate: 23826772, isExponential: true}), // s22 cliff
            CurveMath.Zone({startSupply: 77234575878120538162331648, endSupply: 80217707876828090531315712, rate: 438568450861384640, isExponential: false}), // s22 tread
            CurveMath.Zone({startSupply: 80217707876828090531315712, endSupply: 96261249452193715509526528, rate: 623519, isExponential: true}), // s23 cliff
            CurveMath.Zone({startSupply: 96261249452193715509526528, endSupply: 100000000000000056304336896, rate: 438568450861384640, isExponential: false}), // s23 tread
            CurveMath.Zone({startSupply: 100000000000000056304336896, endSupply: type(uint256).max, rate: 300000000000000000, isExponential: false}) // tail
        ];

        CurveMath.Zone[] memory zones = new CurveMath.Zone[](48);
        for (uint256 i; i < 48; i++) zones[i] = zs[i];

        return PSPFactory.RoundParams({
            name: "Positive Sum Pepes",
            symbol: "PSP",
            curveConfig: CurveMath.CurveConfig({timings: 0, P0: 431045771, zones: zones})
        });
    }
}
