// Reproducible expanded art release. The original Studio compiler stays frozen.
import { readFileSync, writeFileSync } from 'node:fs'
import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { fileURLToPath } from 'node:url'
process.chdir(fileURLToPath(new URL('..', import.meta.url)))
await import('../studio/compiler.js')
const compiler = globalThis.PSPCompiler
const read = p => readFileSync(p, 'utf8')
const old = JSON.parse(read('frontend/src/lib/pepeArt.json'))
const exported = read('studio/expanded/PepeArtData.sol')
const axes = ['expressions', 'eyes', 'hats', 'eyewear', 'items']
const parsed = Object.fromEntries(['head', ...axes].map(axis => [axis, compiler.parseTraitText(read(`studio/expanded/${axis}.txt`)).traits]))
const defaults = JSON.parse(read('studio/src/defaults.js').match(/window.PSP_DEFAULTS = (.*);/s)[1])
const state = { baseGrid: compiler.traitToGrid(parsed.head[0]), axes: Object.fromEntries(axes.map(axis => [axis, parsed[axis].map(t => ({ name: t.name, grid: compiler.traitToGrid(t) }))])), palettes: defaults.palettes }
assert.equal(compiler.compileSolidity(state), exported, 'Studio export differs from text grids / current palettes')
const constants = Object.fromEntries([...exported.matchAll(/bytes internal constant (\w+) = hex"([\da-fA-F]*)";/g)].map(m => [m[1], m[2]]))
const art = {...old, counts: {...old.counts}, base: constants.SPRITE_BASE }
const parts = [art.base]
const starts = {}
const names = []
const legacyNames = Buffer.from(read('src/PepeDescriptor.sol').match(/NAMES = hex"([\da-fA-F]+)"/)[1], 'hex').toString().split('\0').slice(0,-1)
const newNames = { AMAZING: 'Amazing', RAGE: 'Rage', SUS: 'Sus', FUCKMYSHITUP: 'Fuck My Shit Up', READINGGLASSES: 'Reading Glasses', UNIBROW: 'Unibrow', KNIFE: 'Knife' }
for (const [i, axis] of axes.entries()) {
  const key = ['expr','eye','hat','wear','item'][i]
  const labels = [...(i >= 2 ? ['NONE'] : []), ...parsed[axis].map(t => t.name).filter(n => n !== 'NONE')]
  assert(labels.length <= 16)
  const values = labels.map(n => n === 'NONE' ? '' : constants[`${key.toUpperCase()}_${n}`])
  assert(values.every(v => v !== undefined))
  // Record edits to existing slots. They affect release 2 only; legacy data stays frozen.
  for (let j=0;j<old[key].length;j++) if (values[j] !== (old[key][j] ?? '')) console.log(`Updated existing trait in expanded version only: ${axis}/${labels[j]}`)
  art[key] = values; art.counts[key] = values.length
  starts[key.toUpperCase()] = parts.length
  parts.push(...values)
  starts[`${key.toUpperCase()}_NAME`] = names.length
  names.push(...labels.map((n,j) => j < 10 ? legacyNames[i*10+j] : newNames[n]))
}
for (const [i,key] of ['skin','iris','bg'].entries()) {
  starts[`${key.toUpperCase()}_NAME`] = names.length
  names.push(...legacyNames.slice(50+i*10,60+i*10))
}
for (const [key,c] of Object.entries({skins:'SKIN_RAMPS',fixed:'FIXED_SLOTS',irises:'IRIS_COLORS',bgs:'BG_COLORS'})) {
  assert.equal(constants[c], old[key], `Existing ${key} palette changed`)
}
assert.equal(art.base, old.base, 'Existing head pixels changed')
assert(names.every(n => typeof n === 'string' && /^[a-zA-Z0-9 ]+$/.test(n)), 'Metadata names must be JSON safe')
starts.NAME = parts.length
parts.push(...names.map(n => Buffer.from(n).toString('hex')))
const offsets = [0]
for (const p of parts) offsets.push(offsets.at(-1)+p.length/2)
assert(offsets.at(-1)+1 <= 24576, 'Art storage exceeds EIP-170')
const countNames = {expr:'EXPR',eye:'EYE',hat:'HAT',wear:'WEAR',item:'ITEM',skin:'SKIN',iris:'IRIS',bg:'BG'}
const palette = exported.slice(exported.indexOf('    /// @dev skin + iris'))
const sol = `// SPDX-License-Identifier: MIT\npragma solidity 0.8.26;\n\n/// @title ExpandedPepeArt\n/// @notice GENERATED by node script/gen_expanded_art.mjs. Release 2, immutable pixel data.\nlibrary ExpandedPepeArt {\n    uint8 internal constant SIZE = 69;\n${Object.entries(art.counts).map(([k,v])=>`    uint8 internal constant ${countNames[k]}_COUNT = ${v};`).join('\n')}\n${Object.entries(starts).map(([k,v])=>`    uint256 internal constant ${k}_START = ${v};`).join('\n')}\n    bytes internal constant DATA = hex"${parts.join('')}";\n    bytes internal constant OFFSETS = hex"${offsets.map(n=>n.toString(16).padStart(4,'0')).join('')}";\n${['SKIN_RAMPS','FIXED_SLOTS','IRIS_COLORS','BG_COLORS'].map(k=>`    bytes internal constant ${k} = hex"${constants[k]}";`).join('\n')}\n${palette}`
const outputs = {'src/art/ExpandedPepeArt.sol':sol, 'frontend/src/lib/pepeArtExpanded.json':JSON.stringify(art)+'\n'}
for (const [p, data] of Object.entries(outputs)) {
  if (process.argv.includes('--check')) assert.equal(read(p),data,`Regenerate ${p}`)
  else writeFileSync(p,data)
}
console.log(`Expanded art: ${Object.values(art.counts).reduce((a,b)=>a*b,1)} combinations, ${offsets.at(-1)+1} storage bytes; legacy artifacts preserved; export sha256 ${createHash('sha256').update(exported).digest('hex')}`)
