#!/usr/bin/env python3
"""Generate independent small-reserve sine v3 supply fixtures.

Uses 90-digit Decimal arithmetic and composite Simpson integration. Each
integral is checked against twice as many panels. This script imports no
settlement code, generated coefficients, tables, or other curve generators.
It retains the full reserve fraction when evaluating the reference price.
"""
from decimal import Decimal as D, getcontext
from pathlib import Path
import argparse
import math

getcontext().prec = 90
WAD = 10**18
PI = D("3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117067982148")
TWO_PI = 2 * PI
K = D(1000).ln() / (D(11) ** (D(1) / 3) - 1)
LAM_REF = 955 * WAD
BOOT_REF = 450 * WAD


def sine(angle):
    angle %= TWO_PI
    if angle > PI:
        angle -= TWO_PI
    if angle < -PI:
        angle += TWO_PI
    term = total = angle
    for n in range(1, 110):
        term *= -(angle * angle) / D(2 * n * (2 * n + 1))
        total += term
        if abs(term) < D("1e-95"):
            return total
    raise ArithmeticError("sine reference did not converge")


def density_at(phase):
    s = phase - sine(TWO_PI * (phase % 1)) / TWO_PI
    h = (1 + abs(s)) ** (D(1) / 3) - 1
    if s < 0:
        h = -h
    return (-K * h).exp()


def simpson(boot, wavelength, reserve, panels):
    # Integrate over t in [0,1]. Multiplication by reserve follows below.
    def f(i):
        endpoint = D(reserve) * D(i) / D(panels)
        return density_at((endpoint - D(boot)) / D(wavelength))
    total = f(0) + f(panels)
    for i in range(1, panels):
        total += (4 if i % 2 else 2) * f(i)
    return total / (3 * panels)


def supply_reference(boot, wavelength, reserve, price):
    panels = 8
    whole = simpson(boot, wavelength, reserve, panels)
    while panels < 1024:
        panels *= 2
        halves = simpson(boot, wavelength, reserve, panels)
        error = abs(halves - whole) / abs(halves)
        if error <= D("1e-32"):
            return int(D(reserve) * D(WAD) * halves / D(price)), error
        whole = halves
    raise ArithmeticError("Simpson whole-versus-halves check did not converge")


def render():
    rows = []
    worst = D(0)
    for wave in (16, 17, 64, 100, 290, 579):
        prices = (10**9, 75 * 10**12, 10**18) if wave <= 100 else (
            (75 * 10**12, 10**18) if wave == 290 else (10**18,))
        for fraction in (D(0), D("0.37")):
            phase = D(wave) + fraction
            boot = int(phase * phase * D(LAM_REF * LAM_REF) / D(BOOT_REF))
            wavelength = math.isqrt(LAM_REF * LAM_REF * boot // BOOT_REF)
            for price in prices:
                for reserve in (1, 2, 10**6, 10**12, 10**15):
                    expected, error = supply_reference(boot, wavelength, reserve, price)
                    rows.append((boot, wavelength, reserve, price, expected))
                    worst = max(worst, error)
    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity 0.8.26;",
        "",
        "// Generated by scripts/sine_v3_small_reserve.py. Do not hand-edit.",
        "// Independent 90-digit Decimal Simpson integration from R=0.",
        "// Whole-versus-halves convergence is checked at 1e-32 relative.",
        f"// Largest measured split difference: {worst:.4E}.",
        "library SineV3SmallReserveFixtures {",
        "    struct Row { uint256 boot; uint256 wavelength; uint256 reserve; uint256 price; uint256 expected; }",
        f"    function rows() internal pure returns (Row[{len(rows)}] memory r) {{",
    ]
    for i, row in enumerate(rows):
        lines.append(f"        r[{i}] = Row({', '.join(map(str, row))});")
    lines += ["    }", "}", ""]
    return "\n".join(lines), len(rows), worst


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / "test/SineV3SmallReserveFixtures.sol"
    generated, count, worst = render()
    if args.check:
        if not target.exists() or target.read_text() != generated:
            raise SystemExit("Small-reserve fixtures are stale; run scripts/sine_v3_small_reserve.py")
    else:
        target.write_text(generated)
    print(f"{count} independent small-reserve fixtures; worst Simpson split difference {worst:.4E}")


if __name__ == "__main__":
    main()
