#!/usr/bin/env python3
"""Independent 60-digit Decimal reference for the tilted sine curve.

Uses composite Simpson integration, not Solidity's GL8 or fixed-point helpers.
Run from the repository root. --check verifies checked-in vectors byte-for-byte.
No third-party dependencies. No file writes on import.
"""
from decimal import Decimal as D, localcontext
from pathlib import Path
import argparse

PI = D('3.141592653589793238462643383279502884197169399375105820974944592')
WAD = 10**18


def sine(x):
    x %= 2 * PI
    if x > PI:
        x -= 2 * PI
    term = total = x
    for n in range(1, 90):
        term *= -x*x / D(2*n*(2*n+1))
        total += term
        if abs(term) < D('1e-65'):
            break
    return total


def integral(fn, end, n=1024):
    if end == 0:
        return D(0)
    h = end / n
    result = fn(D(0)) + fn(end)
    for i in range(1, n):
        result += (4 if i % 2 else 2) * fn(h*i)
    return result*h/3


def reference(boot, amplitude, points):
    p0, pre, target, pt = D('0.00001'), D('0.004477562267871699'), D(10000), D('0.06')
    boot = D(boot)
    target *= boot / 450
    pre *= 450 / boot
    lam = (target-boot)/3
    B = p0*(pre*boot).exp()
    trend = (pt/B).ln()/3
    amp = D(amplitude)/10000*trend/(2*PI)
    q0 = (1-(-pre*boot).exp())/(pre*p0)
    invg = (-trend).exp()
    def wave_price(t):
        return B*(trend*t-amp*sine(2*PI*t)).exp()
    def density(t):
        return lam/wave_price(t)
    whole = integral(density, D(1))
    # Independent convergence check before trusting the numerical reference.
    finer = integral(density, D(1), 2048)
    assert abs(whole-finer) / finer < D('1e-10')
    whole = finer
    for fraction in points:
        r = boot+lam*D(fraction)
        if r <= boot:
            price = p0*(pre*r).exp()
            q = (1-(-pre*r).exp())/(pre*p0)
        else:
            x = (r-boot)/lam
            k = int(x)
            price = wave_price(x-k)/(invg**k)
            q = q0+whole*(1-invg**k)/(1-invg)+invg**k*integral(density,x-k)
        yield int(r*WAD), int(price*WAD), int(q*WAD)


def generate():
    with localcontext() as ctx:
        ctx.prec = 60
        rows=[]
        for boot in (1,90,450,1_000_000):
            for amp in (0,5000,10000):
                for r,p,q in reference(boot,amp,['0','0.001','0.25','0.5','0.999999','1','1.000001','2.5','3','6']):
                    rows.append((boot*WAD,amp,r,p,q))
    out=['// SPDX-License-Identifier: MIT','pragma solidity 0.8.26;',
         '// Generated by scripts/sine_oracle.py: independent Decimal/Simpson reference.',
         'library SineVectors {',
         f'    function rows() internal pure returns (uint256[5][] memory r) {{ r = new uint256[5][]({len(rows)});']
    for i,row in enumerate(rows):
        out.append(f'        r[{i}] = [uint256({row[0]}), '+', '.join(map(str,row[1:]))+'];')
    out.extend(['    }','}'])
    return '\n'.join(out)+'\n'


def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    output=generate();path=Path(__file__).resolve().parents[1]/'test/SineVectors.sol'
    if args.check:
        if path.read_text()!=output: raise SystemExit('Sine vectors are stale; regenerate them.')
        print('Independent sine vectors match.')
    else:
        path.write_text(output);print(f'Wrote {path}')

if __name__=='__main__': main()
