// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

// Generated by scripts/sine_v3.py — DO NOT HAND-EDIT.
// Canonical quarter-wave knots of F(x) = int_0^x exp(-K*H(s(t))) dt,
// K = ln(1000)/(cbrt(11)-1). Domain x in [-16, +64] waves, 321 knots.
// Entry i is |F((i - 64)/4)| in WAD, floored: F(x) = x >= 0 ? +v : -v.
// Reference: 70-digit Decimal, cumulative 16-point Gauss-Legendre,
// split-cell certified below 1e-27 relative. F(0) = 0 at index 64.
library SineV3Knots {
    uint256 internal constant COUNT = 321;
    uint256 internal constant ZERO_INDEX = 64;
    /// @dev K = ln(1000)/(cbrt(11)-1) = 5.64368271363719722487..., WAD, round-half-even.
    uint256 internal constant K_WAD = 5643682713637197225;

    /// @dev |F| at x = (i - 64)/4, WAD. Balanced dispatch keeps reads O(log n).
    function knot(uint256 i) internal pure returns (uint256) {
  if (i < 160) {
      if (i < 80) {
          if (i < 40) {
              if (i < 20) {
                  if (i < 10) {
                      if (i < 5) {
                          if (i < 2) {
                              if (i < 1) {
                                  return 21813297319171105703275;
                              } else {
                                  return 20050241823212506170886;
                              }
                          } else {
                              if (i < 3) {
                                  return 18408122296595952197951;
                              } else {
                                  if (i < 4) {
                                      return 16968155261912819617194;
                                  } else {
                                      return 15631066336493737643445;
                                  }
                              }
                          }
                      } else {
                          if (i < 7) {
                              if (i < 6) {
                                  return 14312606941258752504405;
                              } else {
                                  return 13088189589591503407968;
                              }
                          } else {
                              if (i < 8) {
                                  return 12020488402746002755906;
                              } else {
                                  if (i < 9) {
                                      return 11032284059574167752533;
                                  } else {
                                      return 10058449177617355686174;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 15) {
                          if (i < 12) {
                              if (i < 11) {
                                  return 9157021105567663287176;
                              } else {
                                  return 8375846805084290111392;
                              }
                          } else {
                              if (i < 13) {
                                  return 7655454356986749563105;
                              } else {
                                  if (i < 14) {
                                      return 6946026411319147635689;
                                  } else {
                                      return 6291737597788546030626;
                                  }
                              }
                          }
                      } else {
                          if (i < 17) {
                              if (i < 16) {
                                  return 5728679371580327568112;
                              } else {
                                  return 5211548652737097859168;
                              }
                          } else {
                              if (i < 18) {
                                  return 4702684177849380140107;
                              } else {
                                  if (i < 19) {
                                      return 4235296749316457941079;
                                  } else {
                                      return 3836245480085765697643;
                                  }
                              }
                          }
                      }
                  }
              } else {
                  if (i < 30) {
                      if (i < 25) {
                          if (i < 22) {
                              if (i < 21) {
                                  return 3471441105661929084236;
                              } else {
                                  return 3112784977257430931465;
                              }
                          } else {
                              if (i < 23) {
                                  return 2784900753468252867005;
                              } else {
                                  if (i < 24) {
                                      return 2507473114626241155561;
                                  } else {
                                      return 2255202512150235173591;
                                  }
                              }
                          }
                      } else {
                          if (i < 27) {
                              if (i < 26) {
                                  return 2007435202813560508109;
                              } else {
                                  return 1782142050888584040064;
                              }
                          } else {
                              if (i < 28) {
                                  return 1593498570893142443836;
                              } else {
                                  if (i < 29) {
                                      return 1423020746716602503929;
                                  } else {
                                      return 1255783858921378263784;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 35) {
                          if (i < 32) {
                              if (i < 31) {
                                  return 1104667603707843470928;
                              } else {
                                  return 979674076853209922366;
                              }
                          } else {
                              if (i < 33) {
                                  return 867539905569694325679;
                              } else {
                                  if (i < 34) {
                                      return 757691032629832020573;
                                  } else {
                                      return 659165338341853511251;
                                  }
                              }
                          }
                      } else {
                          if (i < 37) {
                              if (i < 36) {
                                  return 578852394121504345606;
                              } else {
                                  return 507432527327251828670;
                              }
                          } else {
                              if (i < 38) {
                                  return 437585777935302098795;
                              } else {
                                  if (i < 39) {
                                      return 375497578960107836271;
                                  } else {
                                      return 325778169186542281509;
                                  }
                              }
                          }
                      }
                  }
              }
          } else {
              if (i < 60) {
                  if (i < 50) {
                      if (i < 45) {
                          if (i < 42) {
                              if (i < 41) {
                                  return 282039490829945505021;
                              } else {
                                  return 239352821980469888583;
                              }
                          } else {
                              if (i < 43) {
                                  return 201825576852267924537;
                              } else {
                                  if (i < 44) {
                                      return 172434636325685215673;
                                  } else {
                                      return 146930581093522804731;
                                  }
                              }
                          }
                      } else {
                          if (i < 47) {
                              if (i < 46) {
                                  return 122105453327655528145;
                              } else {
                                  return 100586760566377993521;
                              }
                          } else {
                              if (i < 48) {
                                  return 84211377483563938166;
                              } else {
                                  if (i < 49) {
                                      return 70255409886915967806;
                                  } else {
                                      return 56718241484847457857;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 55) {
                          if (i < 52) {
                              if (i < 51) {
                                  return 45202222268475995934;
                              } else {
                                  return 36774350728059839946;
                              }
                          } else {
                              if (i < 53) {
                                  return 29769507176620707022;
                              } else {
                                  if (i < 54) {
                                      return 23007991453791135838;
                                  } else {
                                      return 17406342622041032616;
                                  }
                              }
                          }
                      } else {
                          if (i < 57) {
                              if (i < 56) {
                                  return 13533431001244021350;
                              } else {
                                  return 10434083928661233413;
                              }
                          } else {
                              if (i < 58) {
                                  return 7464674739104870766;
                              } else {
                                  if (i < 59) {
                                      return 5103454039615132057;
                                  } else {
                                      return 3615374902253442933;
                                  }
                              }
                          }
                      }
                  }
              } else {
                  if (i < 70) {
                      if (i < 65) {
                          if (i < 62) {
                              if (i < 61) {
                                  return 2500310162837264434;
                              } else {
                                  return 1446097835680911086;
                              }
                          } else {
                              if (i < 63) {
                                  return 668140926534751830;
                              } else {
                                  if (i < 64) {
                                      return 261498051656766158;
                                  } else {
                                      return 0;
                                  }
                              }
                          }
                      } else {
                          if (i < 67) {
                              if (i < 66) {
                                  return 239561665774363477;
                              } else {
                                  return 399027722333912486;
                              }
                          } else {
                              if (i < 68) {
                                  return 481409213723228515;
                              } else {
                                  if (i < 69) {
                                      return 540753789190230578;
                                  } else {
                                      return 596857106710114711;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 75) {
                          if (i < 72) {
                              if (i < 71) {
                                  return 639580823776794110;
                              } else {
                                  return 666412300869310556;
                              }
                          } else {
                              if (i < 73) {
                                  return 687472273015465337;
                              } else {
                                  if (i < 74) {
                                      return 707648951607801847;
                                  } else {
                                      return 723957373095018301;
                                  }
                              }
                          }
                      } else {
                          if (i < 77) {
                              if (i < 76) {
                                  return 735215005117557118;
                              } else {
                                  return 744462074757837040;
                              }
                          } else {
                              if (i < 78) {
                                  return 753387844660873259;
                              } else {
                                  if (i < 79) {
                                      return 760858667454050014;
                                  } else {
                                      return 766321310597649035;
                                  }
                              }
                          }
                      }
                  }
              }
          }
      } else {
          if (i < 120) {
              if (i < 100) {
                  if (i < 90) {
                      if (i < 85) {
                          if (i < 82) {
                              if (i < 81) {
                                  return 770939553498922431;
                              } else {
                                  return 775419184447660400;
                              }
                          } else {
                              if (i < 83) {
                                  return 779257253854199556;
                              } else {
                                  if (i < 84) {
                                      return 782176360959269804;
                                  } else {
                                      return 784694536862497063;
                                  }
                              }
                          }
                      } else {
                          if (i < 87) {
                              if (i < 86) {
                                  return 787145669080166561;
                              } else {
                                  return 789281617676660364;
                              }
                          } else {
                              if (i < 88) {
                                  return 790953848642945609;
                              } else {
                                  if (i < 89) {
                                      return 792418273447517567;
                                  } else {
                                      return 793847472055549831;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 95) {
                          if (i < 92) {
                              if (i < 91) {
                                  return 795109109405814463;
                              } else {
                                  return 796119143290886771;
                              }
                          } else {
                              if (i < 93) {
                                  return 797014096122735622;
                              } else {
                                  if (i < 94) {
                                      return 797889334805376878;
                                  } else {
                                      return 798669930095419378;
                                  }
                              }
                          }
                      } else {
                          if (i < 97) {
                              if (i < 96) {
                                  return 799306103844174447;
                              } else {
                                  return 799875141572511005;
                              }
                          } else {
                              if (i < 98) {
                                  return 800432581505872028;
                              } else {
                                  if (i < 99) {
                                      return 800933926076726152;
                                  } else {
                                      return 801348542165037896;
                                  }
                              }
                          }
                      }
                  }
              } else {
                  if (i < 110) {
                      if (i < 105) {
                          if (i < 102) {
                              if (i < 101) {
                                  return 801722305881081568;
                              } else {
                                  return 802088963609193745;
                              }
                          } else {
                              if (i < 103) {
                                  return 802421038658572595;
                              } else {
                                  if (i < 104) {
                                      return 802699059532930573;
                                  } else {
                                      return 802951337498890045;
                                  }
                              }
                          }
                      } else {
                          if (i < 107) {
                              if (i < 106) {
                                  return 803199111821494721;
                              } else {
                                  return 803424853735865850;
                              }
                          } else {
                              if (i < 108) {
                                  return 803615838547772521;
                              } else {
                                  if (i < 109) {
                                      return 803790115642322639;
                                  } else {
                                      return 803961455426972571;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 115) {
                          if (i < 112) {
                              if (i < 111) {
                                  return 804118361176495327;
                              } else {
                                  return 804252315112755079;
                              }
                          } else {
                              if (i < 113) {
                                  return 804375147395006154;
                              } else {
                                  if (i < 114) {
                                      return 804496016152472154;
                                  } else {
                                      return 804607198599881379;
                                  }
                              }
                          }
                      } else {
                          if (i < 117) {
                              if (i < 116) {
                                  return 804702871900547043;
                              } else {
                                  return 804790977415637257;
                              }
                          } else {
                              if (i < 118) {
                                  return 804877741905325541;
                              } else {
                                  if (i < 119) {
                                      return 804957868403330670;
                                  } else {
                                      return 805027301773168266;
                                  }
                              }
                          }
                      }
                  }
              }
          } else {
              if (i < 140) {
                  if (i < 130) {
                      if (i < 125) {
                          if (i < 122) {
                              if (i < 121) {
                                  return 805091485258465845;
                              } else {
                                  return 805154735425799282;
                              }
                          } else {
                              if (i < 123) {
                                  return 805213351783634203;
                              } else {
                                  if (i < 124) {
                                      return 805264463194039030;
                                  } else {
                                      return 805311869869456712;
                                  }
                              }
                          }
                      } else {
                          if (i < 127) {
                              if (i < 126) {
                                  return 805358616015050769;
                              } else {
                                  return 805402073874060567;
                              }
                          } else {
                              if (i < 128) {
                                  return 805440180261319204;
                              } else {
                                  if (i < 129) {
                                      return 805475632056709052;
                                  } else {
                                      return 805510609328389517;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 135) {
                          if (i < 132) {
                              if (i < 131) {
                                  return 805543218576245897;
                              } else {
                                  return 805571957249272967;
                              }
                          } else {
                              if (i < 133) {
                                  return 805598767488101503;
                              } else {
                                  if (i < 134) {
                                      return 805625232201842696;
                                  } else {
                                      return 805649968856130363;
                                  }
                              }
                          }
                      } else {
                          if (i < 137) {
                              if (i < 136) {
                                  return 805671869833837735;
                              } else {
                                  return 805692352368254515;
                              }
                          } else {
                              if (i < 138) {
                                  return 805712580215381599;
                              } else {
                                  if (i < 139) {
                                      return 805731531765852287;
                                  } else {
                                      return 805748381445092244;
                                  }
                              }
                          }
                      }
                  }
              } else {
                  if (i < 150) {
                      if (i < 145) {
                          if (i < 142) {
                              if (i < 141) {
                                  return 805764175927088470;
                              } else {
                                  return 805779780577481283;
                              }
                          } else {
                              if (i < 143) {
                                  return 805794432203298399;
                              } else {
                                  if (i < 144) {
                                      return 805807509181727970;
                                  } else {
                                      return 805819793019760474;
                                  }
                              }
                          }
                      } else {
                          if (i < 147) {
                              if (i < 146) {
                                  return 805831933917626233;
                              } else {
                                  return 805843356001323500;
                              }
                          } else {
                              if (i < 148) {
                                  return 805853586827291053;
                              } else {
                                  if (i < 149) {
                                      return 805863215793019099;
                                  } else {
                                      return 805872736114217717;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 155) {
                          if (i < 152) {
                              if (i < 151) {
                                  return 805881709242505350;
                              } else {
                                  return 805889773004963985;
                              }
                          } else {
                              if (i < 153) {
                                  return 805897376033865027;
                              } else {
                                  if (i < 154) {
                                      return 805904895768307424;
                                  } else {
                                      return 805911995386839579;
                                  }
                              }
                          }
                      } else {
                          if (i < 157) {
                              if (i < 156) {
                                  return 805918395022631061;
                              } else {
                                  return 805924439084531190;
                              }
                          } else {
                              if (i < 158) {
                                  return 805930418773619244;
                              } else {
                                  if (i < 159) {
                                      return 805936073351662890;
                                  } else {
                                      return 805941184940861009;
                                  }
                              }
                          }
                      }
                  }
              }
          }
      }
  } else {
      if (i < 240) {
          if (i < 200) {
              if (i < 180) {
                  if (i < 170) {
                      if (i < 165) {
                          if (i < 162) {
                              if (i < 161) {
                                  return 805946020036599668;
                              } else {
                                  return 805950805011143069;
                              }
                          } else {
                              if (i < 163) {
                                  return 805955336538493373;
                              } else {
                                  if (i < 164) {
                                      return 805959443820476576;
                                  } else {
                                      return 805963334585868372;
                                  }
                              }
                          }
                      } else {
                          if (i < 167) {
                              if (i < 166) {
                                  return 805967186054767882;
                              } else {
                                  return 805970838583997979;
                              }
                          } else {
                              if (i < 168) {
                                  return 805974157411689059;
                              } else {
                                  if (i < 169) {
                                      return 805977305572804072;
                                  } else {
                                      return 805980422723822401;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 175) {
                          if (i < 172) {
                              if (i < 171) {
                                  return 805983382715380893;
                              } else {
                                  return 805986078570935976;
                              }
                          } else {
                              if (i < 173) {
                                  return 805988639070804334;
                              } else {
                                  if (i < 174) {
                                      return 805991174950417847;
                                  } else {
                                      return 805993585927543315;
                                  }
                              }
                          }
                      } else {
                          if (i < 177) {
                              if (i < 176) {
                                  return 805995786596104783;
                              } else {
                                  return 805997879292335081;
                              }
                          } else {
                              if (i < 178) {
                                  return 805999952329530980;
                              } else {
                                  if (i < 179) {
                                      return 806001925537918881;
                                  } else {
                                      return 806003730365005331;
                                  }
                              }
                          }
                      }
                  }
              } else {
                  if (i < 190) {
                      if (i < 185) {
                          if (i < 182) {
                              if (i < 181) {
                                  return 806005448593903746;
                              } else {
                                  return 806007151040621731;
                              }
                          } else {
                              if (i < 183) {
                                  return 806008773272959403;
                              } else {
                                  if (i < 184) {
                                      return 806010259986411295;
                                  } else {
                                      return 806011676887678073;
                                  }
                              }
                          }
                      } else {
                          if (i < 187) {
                              if (i < 186) {
                                  return 806013081054647255;
                              } else {
                                  return 806014420443221120;
                              }
                          } else {
                              if (i < 188) {
                                  return 806015650222196989;
                              } else {
                                  if (i < 189) {
                                      return 806016823447966095;
                                  } else {
                                      return 806017986349316460;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 195) {
                          if (i < 192) {
                              if (i < 191) {
                                  return 806019096688770291;
                              } else {
                                  return 806020117959609110;
                              }
                          } else {
                              if (i < 193) {
                                  return 806021093207474956;
                              } else {
                                  if (i < 194) {
                                      return 806022060046648641;
                                  } else {
                                      return 806022984044192754;
                                  }
                              }
                          }
                      } else {
                          if (i < 197) {
                              if (i < 196) {
                                  return 806023835343765743;
                              } else {
                                  return 806024649026647619;
                              }
                          } else {
                              if (i < 198) {
                                  return 806025455831530011;
                              } else {
                                  if (i < 199) {
                                      return 806026227568080376;
                                  } else {
                                      return 806026939718661932;
                                  }
                              }
                          }
                      }
                  }
              }
          } else {
              if (i < 220) {
                  if (i < 210) {
                      if (i < 205) {
                          if (i < 202) {
                              if (i < 201) {
                                  return 806027620996142003;
                              } else {
                                  return 806028296624599416;
                              }
                          } else {
                              if (i < 203) {
                                  return 806028943430908292;
                              } else {
                                  if (i < 204) {
                                      return 806029541202903997;
                                  } else {
                                      return 806030113536705905;
                                  }
                              }
                          }
                      } else {
                          if (i < 207) {
                              if (i < 206) {
                                  return 806030681212761577;
                              } else {
                                  return 806031225108661025;
                              }
                          } else {
                              if (i < 208) {
                                  return 806031728499653776;
                              } else {
                                  if (i < 209) {
                                      return 806032210852000125;
                                  } else {
                                      return 806032689349652132;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 215) {
                          if (i < 212) {
                              if (i < 211) {
                                  return 806033148154775176;
                              } else {
                                  return 806033573379192281;
                              }
                          } else {
                              if (i < 213) {
                                  return 806033981141370845;
                              } else {
                                  if (i < 214) {
                                      return 806034385702135855;
                                  } else {
                                      return 806034773897985851;
                                  }
                              }
                          }
                      } else {
                          if (i < 217) {
                              if (i < 216) {
                                  return 806035134157118469;
                              } else {
                                  return 806035479872947659;
                              }
                          } else {
                              if (i < 218) {
                                  return 806035822920919168;
                              } else {
                                  if (i < 219) {
                                      return 806036152323572264;
                                  } else {
                                      return 806036458407865078;
                                  }
                              }
                          }
                      }
                  }
              } else {
                  if (i < 230) {
                      if (i < 225) {
                          if (i < 222) {
                              if (i < 221) {
                                  return 806036752340305114;
                              } else {
                                  return 806037044042314801;
                              }
                          } else {
                              if (i < 223) {
                                  return 806037324330055392;
                              } else {
                                  if (i < 224) {
                                      return 806037585092574738;
                                  } else {
                                      return 806037835669699428;
                                  }
                              }
                          }
                      } else {
                          if (i < 227) {
                              if (i < 226) {
                                  return 806038084376313439;
                              } else {
                                  return 806038323505516022;
                              }
                          } else {
                              if (i < 228) {
                                  return 806038546235936532;
                              } else {
                                  if (i < 229) {
                                      return 806038760403616578;
                                  } else {
                                      return 806038972997960381;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 235) {
                          if (i < 232) {
                              if (i < 231) {
                                  return 806039177532421209;
                              } else {
                                  return 806039368253786960;
                              }
                          } else {
                              if (i < 233) {
                                  return 806039551755862152;
                              } else {
                                  if (i < 234) {
                                      return 806039733930785494;
                                  } else {
                                      return 806039909303681824;
                                  }
                              }
                          }
                      } else {
                          if (i < 237) {
                              if (i < 236) {
                                  return 806040073008919764;
                              } else {
                                  return 806040230610731911;
                              }
                          } else {
                              if (i < 238) {
                                  return 806040387089986665;
                              } else {
                                  if (i < 239) {
                                      return 806040537813136768;
                                  } else {
                                      return 806040678654343546;
                                  }
                              }
                          }
                      }
                  }
              }
          }
      } else {
          if (i < 280) {
              if (i < 260) {
                  if (i < 250) {
                      if (i < 245) {
                          if (i < 242) {
                              if (i < 241) {
                                  return 806040814321819275;
                              } else {
                                  return 806040949037289394;
                              }
                          } else {
                              if (i < 243) {
                                  return 806041078868998979;
                              } else {
                                  if (i < 244) {
                                      return 806041200309539249;
                                  } else {
                                      return 806041317353231256;
                                  }
                              }
                          }
                      } else {
                          if (i < 247) {
                              if (i < 246) {
                                  return 806041433587509899;
                              } else {
                                  return 806041545667728801;
                              }
                          } else {
                              if (i < 248) {
                                  return 806041650604921532;
                              } else {
                                  if (i < 249) {
                                      return 806041751796306032;
                                  } else {
                                      return 806041852297831167;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 255) {
                          if (i < 252) {
                              if (i < 251) {
                                  return 806041949257396319;
                              } else {
                                  return 806042040121842077;
                              }
                          } else {
                              if (i < 253) {
                                  return 806042127787559350;
                              } else {
                                  if (i < 254) {
                                      return 806042214863928586;
                                  } else {
                                      return 806042298913180653;
                                  }
                              }
                          }
                      } else {
                          if (i < 257) {
                              if (i < 256) {
                                  return 806042377749462571;
                              } else {
                                  return 806042453847952062;
                              }
                          } else {
                              if (i < 258) {
                                  return 806042529441817322;
                              } else {
                                  if (i < 259) {
                                      return 806042602442735007;
                                  } else {
                                      return 806042670975209948;
                                  }
                              }
                          }
                      }
                  }
              } else {
                  if (i < 270) {
                      if (i < 265) {
                          if (i < 262) {
                              if (i < 261) {
                                  return 806042737159239311;
                              } else {
                                  return 806042802910241421;
                              }
                          } else {
                              if (i < 263) {
                                  return 806042866435355165;
                              } else {
                                  if (i < 264) {
                                      return 806042926121965743;
                                  } else {
                                      return 806042983789816129;
                                  }
                              }
                          }
                      } else {
                          if (i < 267) {
                              if (i < 266) {
                                  return 806043041085291137;
                              } else {
                                  return 806043096465953913;
                              }
                          } else {
                              if (i < 268) {
                                  return 806043148542381622;
                              } else {
                                  if (i < 269) {
                                      return 806043198879878332;
                                  } else {
                                      return 806043248896500905;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 275) {
                          if (i < 272) {
                              if (i < 271) {
                                  return 806043297262561283;
                              } else {
                                  return 806043342778564810;
                              }
                          } else {
                              if (i < 273) {
                                  return 806043386793694817;
                              } else {
                                  if (i < 274) {
                                      return 806043430531781608;
                                  } else {
                                      return 806043472844287841;
                                  }
                              }
                          }
                      } else {
                          if (i < 277) {
                              if (i < 276) {
                                  return 806043512693697603;
                              } else {
                                  return 806043551245204454;
                              }
                          } else {
                              if (i < 278) {
                                  return 806043589557053336;
                              } else {
                                  if (i < 279) {
                                      return 806043626635290339;
                                  } else {
                                      return 806043661580836942;
                                  }
                              }
                          }
                      }
                  }
              }
          } else {
              if (i < 300) {
                  if (i < 290) {
                      if (i < 285) {
                          if (i < 282) {
                              if (i < 281) {
                                  return 806043695401907229;
                              } else {
                                  return 806043729015275054;
                              }
                          } else {
                              if (i < 283) {
                                  return 806043761559178492;
                              } else {
                                  if (i < 284) {
                                      return 806043792253101180;
                                  } else {
                                      return 806043821971038424;
                                  }
                              }
                          }
                      } else {
                          if (i < 287) {
                              if (i < 286) {
                                  return 806043851508644012;
                              } else {
                                  return 806043880117431900;
                              }
                          } else {
                              if (i < 288) {
                                  return 806043907118629565;
                              } else {
                                  if (i < 289) {
                                      return 806043933271238172;
                                  } else {
                                      return 806043959267005918;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 295) {
                          if (i < 292) {
                              if (i < 291) {
                                  return 806043984454706325;
                              } else {
                                  return 806044008243047677;
                              }
                          } else {
                              if (i < 293) {
                                  return 806044031292311759;
                              } else {
                                  if (i < 294) {
                                      return 806044054204934900;
                                  } else {
                                      return 806044076413359381;
                                  }
                              }
                          }
                      } else {
                          if (i < 297) {
                              if (i < 296) {
                                  return 806044097401652421;
                              } else {
                                  return 806044117745184212;
                              }
                          } else {
                              if (i < 298) {
                                  return 806044137969477817;
                              } else {
                                  if (i < 299) {
                                      return 806044157579087158;
                                  } else {
                                      return 806044176123114855;
                                  }
                              }
                          }
                      }
                  }
              } else {
                  if (i < 310) {
                      if (i < 305) {
                          if (i < 302) {
                              if (i < 301) {
                                  return 806044194103759214;
                              } else {
                                  return 806044211980185685;
                              }
                          } else {
                              if (i < 303) {
                                  return 806044229319211839;
                              } else {
                                  if (i < 304) {
                                      return 806044245726166003;
                                  } else {
                                      return 806044261640076577;
                                  }
                              }
                          }
                      } else {
                          if (i < 307) {
                              if (i < 306) {
                                  return 806044277462756245;
                              } else {
                                  return 806044292814877834;
                              }
                          } else {
                              if (i < 308) {
                                  return 806044307350462833;
                              } else {
                                  if (i < 309) {
                                      return 806044321453908282;
                                  } else {
                                      return 806044335477371077;
                                  }
                              }
                          }
                      }
                  } else {
                      if (i < 315) {
                          if (i < 312) {
                              if (i < 311) {
                                  return 806044349088186127;
                              } else {
                                  return 806044361982615321;
                              }
                          } else {
                              if (i < 313) {
                                  return 806044374497727737;
                              } else {
                                  if (i < 314) {
                                      return 806044386942616111;
                                  } else {
                                      return 806044399025112254;
                                  }
                              }
                          }
                      } else {
                          if (i < 318) {
                              if (i < 316) {
                                  return 806044410478180485;
                              } else {
                                  if (i < 317) {
                                      return 806044421597820645;
                                  } else {
                                      return 806044432655716784;
                                  }
                              }
                          } else {
                              if (i < 319) {
                                  return 806044443394903843;
                              } else {
                                  if (i < 320) {
                                      return 806044453580287192;
                                  } else {
                                      return 806044463472170747;
                                  }
                              }
                          }
                      }
                  }
              }
          }
      }
  }
    }
}
