// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

// Generated by scripts/sine_v3.py. Do not edit by hand.
library SineV3DataInfo {
    uint256 internal constant COUNT = 4938;
    uint256 internal constant ZERO_INDEX = 711;
    uint256 internal constant FIRST_HALF_INDEX = 453;
    uint256 internal constant FIRST_QUARTER_INDEX = 707;
    uint256 internal constant LAST_QUARTER_INDEX = 715;
    uint256 internal constant LAST_HALF_INDEX = 969;
    uint256 internal constant NEGATIVE_BYTES = 17064;
    bytes32 internal constant HASH0 = 0x569f621f0f1d60c6da1926faca56be9747e40f91af9e7d4b826c0fc034c4fc8c;
    uint256 internal constant START0 = 0;
    uint256 internal constant BYTES0 = 21993;
    bytes32 internal constant HASH1 = 0x9157089079151d496cf7449c803566c75b27ffe098015a6debe34087ea4a08a6;
    uint256 internal constant START1 = 21992;
    uint256 internal constant BYTES1 = 22001;
    bytes32 internal constant HASH2 = 0x2a902a55e1fb1624104585ee0e048ea21a3d8a57b76abe0341eb498aadd51103;
    uint256 internal constant START2 = 43992;
    uint256 internal constant BYTES2 = 22001;
    bytes32 internal constant HASH3 = 0x59c803ae3f53dc0e9cabdbf01e07ca40b11526c4ae28b2fe65c0b786824d0e42;
    uint256 internal constant START3 = 65992;
    uint256 internal constant BYTES3 = 18705;
}
