// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @title VectorBaseArt — traced vector pepe base + palettes (GENERATED by
///        script/trace_vector.py 2026-08-24 — do not edit by hand).
/// @dev Base head traced from script/assets/pepe_ref.jpg at 480px, feature
///      zones wiped exactly like the pixel pipeline; regions potraced to
///      smooth paths. Palette constants identical to PepeArtData.
library VectorBaseArt {
    uint16 public constant SIZE = 480;

    /// @dev nostril nudge from the vector studio (48-grid cells, x10 used)
    int16 internal constant NOSTRIL_OFF_X = 0;
    int16 internal constant NOSTRIL_OFF_Y = 0;

    /// @dev base skin region (slot 2)
    string internal constant BASE_SKIN = "M 257 111 c -2 0 -6 2 -8 3 l -4 2 2 1 c 11 7 26 27 22 29 -1 2 -3 0 -8 -7 -10 -15 -25 -24 -42 -26 -12 -2 -32 0 -36 3 0 1 -1 1 -1 1 0 -1 -1 0 -2 0 -2 1 -3 2 -3 2 0 -2 -11 5 -16 9 -7 6 -11 10 -16 17 -2 3 -4 5 -4 5 -2 0 -11 20 -11 25 0 1 0 2 -1 2 -1 0 -6 5 -12 11 -17 18 -19 21 -25 32 -12 27 -15 59 -8 87 1 3 2 6 2 7 1 1 1 1 1 1 0 0 0 2 1 3 0 1 0 3 1 3 0 1 1 3 1 5 0 2 1 4 2 5 1 1 3 4 4 6 0 2 3 6 4 8 2 3 5 7 6 9 7 14 31 37 42 39 0 1 1 1 3 2 1 0 3 1 5 2 2 0 4 0 4 1 1 0 3 0 5 1 2 0 5 0 5 1 1 0 2 1 3 1 5 1 12 2 19 3 14 1 73 2 87 1 13 -2 15 -2 16 -2 0 -1 3 -1 6 -1 3 -1 6 -1 6 -2 1 0 2 -1 3 -1 2 0 4 0 6 -1 1 -1 5 -2 8 -3 18 -7 31 -15 43 -27 5 -4 9 -8 10 -8 2 0 7 -7 11 -14 2 -6 3 -12 2 -18 -1 -2 0 -3 4 -10 7 -9 8 -13 5 -17 l -2 -3 2 -2 c 3 -4 3 -7 -2 -11 -3 -3 -3 -3 -3 -8 0 -8 -2 -12 -10 -19 l -6 -5 2 -3 c 3 -3 3 -4 -1 -8 l -2 -3 2 -3 c 2 -1 4 -5 6 -8 3 -8 3 -24 -1 -31 l -2 -5 3 -3 c 5 -5 4 -9 -5 -14 -2 -2 -5 -5 -6 -8 -5 -7 -8 -10 -15 -14 l -7 -3 -22 0 c -15 0 -22 0 -21 -1 0 -1 0 -1 1 -1 0 1 1 0 3 -1 1 0 3 -1 3 0 1 0 2 0 2 -1 2 -1 5 -1 9 -1 l 4 0 -3 -5 c -4 -5 -11 -12 -11 -11 0 0 -3 -2 -6 -5 -3 -3 -6 -5 -7 -5 0 0 -1 -1 -2 -1 -1 -1 -1 -2 -2 -2 0 0 -2 0 -3 -1 -10 -4 -30 -6 -40 -4z m 19 251 c -8 1 -41 2 -49 1 -13 -2 -9 -3 23 -3 33 0 33 0 26 2z";
    /// @dev dark outline (slot 4)
    string internal constant BASE_DARK = "M 255 107 c -6 1 -13 4 -14 6 -1 0 -5 -1 -9 -2 -27 -9 -61 -1 -80 19 -10 10 -17 21 -22 35 -2 5 -4 7 -15 18 -7 7 -14 15 -17 18 -23 29 -29 76 -15 118 10 31 37 66 59 77 18 10 42 13 93 15 52 1 75 -3 104 -17 33 -15 58 -47 54 -66 -1 -2 0 -3 4 -10 7 -9 8 -13 5 -17 l -2 -3 2 -2 c 4 -4 2 -10 -3 -12 -2 -2 -2 -2 -2 -7 0 -7 -2 -12 -10 -19 l -6 -6 2 -2 c 3 -3 1 -8 -2 -10 -1 -1 -1 -1 1 -4 2 -1 4 -5 6 -8 3 -8 3 -24 -1 -31 l -2 -5 3 -3 c 2 -2 3 -4 3 -5 0 -3 -5 -9 -9 -11 -2 -1 -4 -3 -6 -6 -6 -11 -18 -19 -32 -21 -6 -1 -7 -1 -11 -7 -9 -12 -25 -25 -36 -29 -12 -5 -31 -6 -42 -3z m 34 6 c 3 0 7 2 8 2 1 1 3 1 3 1 1 0 1 1 2 2 1 0 2 1 2 1 1 0 4 2 7 5 3 3 6 5 6 5 0 -1 7 6 11 11 l 3 5 -4 0 c -4 0 -7 0 -9 1 0 1 -1 1 -2 1 0 -1 -2 0 -3 0 -2 1 -3 2 -3 1 -1 0 -1 0 -1 1 -1 1 6 1 21 1 l 22 0 7 3 c 7 4 10 7 15 14 1 3 4 6 6 8 9 5 10 9 5 14 l -3 3 2 5 c 4 7 4 23 1 31 -2 3 -4 7 -6 8 l -2 3 2 3 c 4 4 4 5 1 8 l -2 3 6 5 c 8 7 10 11 10 19 0 5 0 5 3 8 5 4 5 7 2 11 l -2 2 2 3 c 3 4 2 8 -5 17 -4 7 -5 8 -4 10 1 6 0 12 -2 18 -4 7 -9 14 -11 14 -1 0 -5 4 -10 8 -12 12 -25 20 -43 27 -3 1 -7 2 -8 3 -2 1 -4 1 -6 1 -1 0 -2 1 -3 1 0 1 -3 1 -6 2 -3 0 -6 0 -6 1 -1 0 -3 0 -16 2 -14 1 -73 0 -87 -1 -7 -1 -14 -2 -19 -3 -1 0 -2 -1 -3 -1 0 -1 -3 -1 -5 -1 -2 -1 -4 -1 -5 -1 0 -1 -2 -1 -4 -1 -2 -1 -4 -2 -5 -2 -2 -1 -3 -1 -3 -2 -11 -2 -35 -25 -42 -39 -1 -2 -4 -6 -6 -9 -1 -2 -4 -6 -4 -8 -1 -2 -3 -5 -4 -6 -1 -1 -2 -3 -2 -5 0 -2 -1 -4 -1 -5 -1 0 -1 -2 -1 -3 -1 -1 -1 -3 -1 -3 0 0 0 0 -1 -1 0 -1 -1 -4 -2 -7 -7 -28 -4 -60 8 -87 6 -11 8 -14 25 -32 6 -6 11 -11 12 -11 1 0 1 -1 1 -2 0 -5 9 -25 11 -25 0 0 2 -2 4 -5 5 -7 9 -11 16 -17 5 -4 16 -11 16 -9 0 0 1 -1 3 -2 1 0 2 -1 2 0 0 0 1 0 1 -1 4 -3 24 -5 36 -3 17 2 32 11 42 26 5 7 7 9 8 7 4 -2 -11 -22 -22 -29 l -2 -1 4 -2 c 9 -4 29 -5 40 -1z M 220 361 c 7 2 11 2 30 2 12 0 21 0 26 -1 7 -2 7 -2 -26 -2 -23 0 -32 1 -30 1z";

    /// @dev skin ramps: 8 skins x (2,3,4,10) x 3B
    bytes internal constant SKIN_RAMPS = hex"62C8758BD07C2D5034244229D4AF37F0DA7BA8842B6B502AB9C4B0D6DED06E7A664A3E365FE3D0A9F4E835B5A42E6E743B4C6B5A6F9425314A2E2A3AB0B0B05A6F9425314A2E2A3AFF95005A6F9425314A2E2A3A1370005A6F9425314A2E2A3A";

    /// @dev fixed slots (5,7,8,9,11,12,13,14)
    bytes internal constant FIXED_SLOTS = hex"FEFEFEC8626D432122D0483EE8B93E8C6A1D001EFF23282D";

    /// @dev iris colors override slot 6
    bytes internal constant IRIS_COLORS = hex"3F575B549EC7C8872B2E8B579E2B2B1414161100FF";

    /// @dev background colors override slot 15
    bytes internal constant BG_COLORS = hex"74C0DAB5E8C9F5C8A8C9B8E8F09A668E2F3C1821380A0A0DFFF824FF0AF7";

    /// @dev full 16-slot palette (verbatim mirror of PepeArtData.palette)
    function palette(uint8 skinId, uint8 irisId, uint8 bgId)
        internal
        pure
        returns (bytes3[16] memory m)
    {
        bytes memory skins = SKIN_RAMPS;
        bytes memory slots = FIXED_SLOTS;
        for (uint256 i; i < 4; ++i) {
            uint256 o = uint256(skinId) * 12 + i * 3;
            m[[2, 3, 4, 10][i]] = bytes3(
                (uint24(uint8(skins[o])) << 16)
                    | (uint24(uint8(skins[o + 1])) << 8)
                    | uint24(uint8(skins[o + 2]))
            );
        }
        for (uint256 i; i < 8; ++i) {
            uint256 o = i * 3;
            m[[5, 7, 8, 9, 11, 12, 13, 14][i]] = bytes3(
                (uint24(uint8(slots[o])) << 16)
                    | (uint24(uint8(slots[o + 1])) << 8)
                    | uint24(uint8(slots[o + 2]))
            );
        }
        uint256 io = uint256(irisId) * 3;
        m[6] = bytes3(
            (uint24(uint8(IRIS_COLORS[io])) << 16)
                | (uint24(uint8(IRIS_COLORS[io + 1])) << 8)
                | uint24(uint8(IRIS_COLORS[io + 2]))
        );
        uint256 bo = uint256(bgId) * 3;
        m[15] = bytes3(
            (uint24(uint8(BG_COLORS[bo])) << 16)
                | (uint24(uint8(BG_COLORS[bo + 1])) << 8)
                | uint24(uint8(BG_COLORS[bo + 2]))
        );
    }
}
